import type { MissionSector } from "../../core/types";
import { parseMap } from "../maps";
import { g, wave } from "../waves";
// Sector VII, Kreislauf: ring maps without a reactor. Waves start on a timer, enemies
// circle until they die, and too many at once overload the ring.
const UMLAUFBAHN = parseMap("umlaufbahn", "Umlaufbahn", [
  "..................",
  "..S===========....",
  "..=..........=....",
  "..=..#....#..=....",
  "..=..........====.",
  "..=.............=.",
  "..=....##.......=.",
  "..=.............=.",
  "..=..........====.",
  "..=..#....#..=....",
  "..============....",
  "..................",
], "orbit");
const DOPPELSCHLEIFE = parseMap("doppelschleife", "Doppelschleife", [
  "....................",
  ".S=======..=======..",
  ".=......=..=.....=..",
  ".=......=..=.....=..",
  ".=..#...=..=..#..=..",
  ".=......====.....=..",
  ".=...............=..",
  ".=...##......##..=..",
  ".=...............=..",
  ".=...............=..",
  ".=================..",
  "....................",
], "rift");
const MAHLSTROM = parseMap("mahlstrom", "Mahlstrom", [
  "....................",
  ".S=====.....======..",
  ".=....=.....=....=..",
  ".=....=.....=....=..",
  ".=....=.#...=....=..",
  ".=....=.....=....=..",
  ".=....=======....=..",
  ".=...............=..",
  ".=.......======..=..",
  ".=.......=....=..=..",
  ".=.......=..#.=..=..",
  ".=========....====..",
  "....................",
], "rift");
export const KREISLAUF: MissionSector = {
  id: "circle",
  name: "Kreislauf",
  missions: [
    {
      id: "umlaufbahn",
      name: "Umlaufbahn",
      focus: "Gegner kreisen, bis sie fallen. Halte den Ring unter dem Limit",
      map: UMLAUFBAHN,
      circle: { interval: 22, limit: 30, earlyBonus: 2 },
      waves: [
        wave(30, g("drone", 10, 0.9)),
        wave(35, g("drone", 12, 0.7), g("runner", 4, 0.8, 6)),
        wave(40, g("tank", 4, 2), g("drone", 10, 0.6, 3)),
        wave(45, g("runner", 16, 0.5)),
        wave(50, g("drone", 20, 0.45), g("tank", 4, 1.6, 4)),
        wave(55, g("glider", 10, 0.6), g("runner", 10, 0.5, 4)),
        wave(60, g("tank", 10, 1.1), g("drone", 16, 0.4, 3)),
        wave(80, g("tank", 8, 1.2), g("boss", 1, 1, 6), g("runner", 20, 0.4, 8)),
      ],
      startingCredits: 400,
      reactorEnergy: 20,
      hpGrowth: 0.35,
    },
    {
      id: "doppelschleife",
      name: "Doppelschleife",
      focus: "Die Einbuchtung bündelt zwei Bahnen. Früh rufen lohnt sich",
      map: DOPPELSCHLEIFE,
      circle: { interval: 20, limit: 30, earlyBonus: 3 },
      waves: [
        wave(30, g("drone", 12, 0.8)),
        wave(35, g("splitter", 6, 1.2), g("drone", 8, 0.6, 4)),
        wave(40, g("runner", 14, 0.5), g("glider", 6, 0.7, 4)),
        wave(45, g("slime", 6, 1.3), g("drone", 12, 0.5, 3)),
        wave(50, g("tank", 8, 1.2), g("skater", 8, 0.6, 4)),
        wave(55, g("splitter", 10, 0.9), g("glider", 10, 0.5, 5)),
        wave(60, g("aegis", 8, 1), g("runner", 16, 0.4, 3)),
        wave(65, g("bulwark", 6, 1.4), g("drone", 20, 0.35, 2)),
        wave(90, g("boss", 2, 4), g("splitter", 10, 0.8, 3), g("skater", 14, 0.45, 6)),
      ],
      startingCredits: 450,
      reactorEnergy: 20,
      hpGrowth: 0.45,
    },
    {
      id: "mahlstrom",
      name: "Mahlstrom",
      focus: "Zwei Einbuchtungen, schnelle Wellen. Heiler und Anführer zuerst",
      map: MAHLSTROM,
      circle: { interval: 18, limit: 35, earlyBonus: 3 },
      waves: [
        wave(30, g("drone", 14, 0.7)),
        wave(35, g("runner", 12, 0.5), g("tank", 3, 1.8, 4)),
        wave(40, g("mender", 4, 1.5), g("drone", 14, 0.5, 2)),
        wave(45, g("glider", 12, 0.5), g("splitter", 6, 1, 4)),
        wave(50, g("warlord", 2, 3), g("runner", 16, 0.4, 2)),
        wave(55, g("bulwark", 6, 1.3), g("mender", 4, 1.2, 3)),
        wave(60, g("berserker", 6, 1.2), g("glider", 12, 0.45, 4)),
        wave(65, g("aegis", 10, 0.9), g("skater", 14, 0.45, 3)),
        wave(70, g("warlord", 3, 2), g("bulwark", 8, 1.1, 2), g("drone", 20, 0.3, 5)),
        wave(100, g("boss", 3, 3), g("berserker", 8, 1, 4), g("runner", 22, 0.33, 8)),
      ],
      startingCredits: 500,
      reactorEnergy: 20,
      hpGrowth: 0.3,
    },
  ],
};
