import type { MissionSector } from "../../core/types";
import { parseMap } from "../maps";
import { g, wave } from "../waves";
// Sector VIII, Zahnwerk: ring maps in a clockwork. Cogs gain speed with every lap, pistons
// harden with every lap, so both have to die early.
// Crenellated ring: three teeth on the top and bottom edge form pockets that reach several legs.
const ZAHNKRANZ = parseMap("zahnkranz", "Zahnkranz", [
  "...............",
  "...===.===.===.",
  ".S==.===.===.=.",
  ".=...........=.",
  ".=...........=.",
  ".=..#..#..#..=.",
  ".=...........=.",
  ".=...........=.",
  ".=.===.===.===.",
  ".===.===.===...",
  "...............",
], "gear");
// Long snake ring: four one-cell corridors fold the ring, so each corridor tower sees two legs.
const HEMMUNG = parseMap("hemmung", "Hemmung", [
  ".....................",
  ".S==.=======.=======.",
  ".=.=.=.....=.=.....=.",
  ".=.=.=.===.=.=.===.=.",
  ".=.=.=.=.=.=.=.=.=.=.",
  ".=.=.=.=.=.=.=.=.=.=.",
  ".=.===.=.=.===.=.=.=.",
  ".=.....=.=.....=.=.=.",
  ".=======.=======.===.",
  ".....................",
], "gear");
// Hourglass ring: both sides pinch in until a three-cell lane between the tips bundles four legs.
const UNRUH = parseMap("unruh", "Unruh", [
  "...............",
  ".=============.",
  ".=...........=.",
  ".S====...=====.",
  ".....=...=.....",
  "#....=...=....#",
  ".....=...=.....",
  ".=====...=====.",
  ".=...........=.",
  ".=============.",
  "...............",
], "gear");
// Plus-shaped ring: four arms with three-cell lanes and a hub where all four inner corners meet.
const PLANETENRAD = parseMap("planetenrad", "Planetenrad", [
  "...............",
  ".....S====.....",
  "..#..=...=..#..",
  ".....=...=.....",
  ".....=...=.....",
  ".=====...=====.",
  ".=...........=.",
  ".=...........=.",
  ".=...........=.",
  ".=====...=====.",
  ".....=...=.....",
  ".....=...=.....",
  "..#..=...=..#..",
  ".....=====.....",
  "...............",
], "gear");
// Hooked ring: a notch from the left edge bends down and back, folding one lane into the ring.
const UHRWERK = parseMap("uhrwerk", "Uhrwerk", [
  "...............",
  ".S============.",
  ".=...........=.",
  ".=========...=.",
  ".........=...=.",
  ".=======.=.#.=.",
  ".=.....=.=...=.",
  ".=.....===...=.",
  ".=.#.........=.",
  ".=============.",
  "...............",
], "gear");
export const ZAHNWERK: MissionSector = {
  id: "gear",
  name: "Zahnwerk",
  missions: [
    {
      id: "zahnkranz",
      name: "Zahnkranz",
      focus: "Zahnräder werden schneller, je länger sie kreisen. Kryo, Gravitron und Tesla bremsen sie früh",
      map: ZAHNKRANZ,
      circle: { interval: 20, limit: 36, earlyBonus: 3 },
      waves: [
        wave(30, g("drone", 10, 0.9)),
        wave(35, g("drone", 12, 0.7), g("runner", 4, 0.8, 6)),
        wave(40, g("cog", 6, 1.2), g("drone", 8, 0.6, 3)),
        wave(45, g("runner", 14, 0.5), g("cog", 6, 1, 4)),
        wave(50, g("tank", 4, 2), g("cog", 8, 0.9, 3)),
        wave(55, g("splitter", 6, 1.1), g("cog", 10, 0.7, 4)),
        wave(60, g("tank", 8, 1.2), g("cog", 12, 0.6, 3)),
        wave(65, g("aegis", 8, 1), g("cog", 12, 0.5, 3)),
        wave(70, g("bulwark", 6, 1.4), g("runner", 16, 0.4, 2)),
        wave(90, g("tank", 8, 1.1), g("cog", 12, 0.5, 4), g("runner", 10, 0.45, 8)),
      ],
      startingCredits: 500,
      reactorEnergy: 20,
      hpGrowth: 0.3,
    },
    {
      id: "hemmung",
      name: "Hemmung",
      focus: "Kolbenpanzer härten mit jeder Runde. Zerfall, Fokus und Lanze müssen sie in der ersten Runde fällen",
      map: HEMMUNG,
      circle: { interval: 18, limit: 32, earlyBonus: 3 },
      waves: [
        wave(30, g("drone", 10, 0.8)),
        wave(35, g("piston", 3, 1.8), g("drone", 8, 0.6, 3)),
        wave(40, g("glider", 6, 0.8), g("runner", 10, 0.5, 4)),
        wave(45, g("piston", 4, 1.6), g("cog", 5, 1, 5)),
        wave(50, g("splitter", 6, 1), g("glider", 6, 0.7, 4)),
        wave(55, g("piston", 6, 1.4), g("drone", 12, 0.45, 4)),
        wave(60, g("stormbird", 6, 0.9), g("cog", 8, 0.7, 3)),
        wave(65, g("piston", 8, 1.2), g("runner", 14, 0.4, 3)),
        wave(70, g("bulwark", 7, 1.2), g("glider", 10, 0.5, 3)),
        wave(90, g("piston", 8, 1.1), g("stormbird", 6, 0.8, 4), g("cog", 8, 0.6, 8)),
      ],
      startingCredits: 550,
      reactorEnergy: 20,
      hpGrowth: 0.35,
    },
    {
      id: "unruh",
      name: "Unruh",
      focus: "Kurze Takte, Welle 8 ist ein Echo mit fünffachen HP. Die Taille hält vier Bahnen unter Feuer",
      map: UNRUH,
      circle: { interval: 16, limit: 35, earlyBonus: 3 },
      waves: [
        wave(30, g("drone", 10, 0.8)),
        wave(35, g("cog", 6, 1.2), g("runner", 8, 0.6, 4)),
        wave(40, g("glider", 8, 0.7), g("tank", 3, 1.8, 3)),
        wave(45, g("piston", 4, 1.6), g("drone", 12, 0.5, 3)),
        wave(50, g("moth", 10, 0.6), g("cog", 10, 0.7, 3)),
        wave(55, g("mender", 4, 1.4), g("runner", 14, 0.45, 2)),
        wave(60, g("splitter", 8, 1), g("piston", 6, 1.3, 4)),
        { ...wave(65, g("cog", 10, 0.5), g("glider", 6, 0.6, 3)), hpMultiplier: 5 },
        wave(70, g("bulwark", 6, 1.2), g("moth", 8, 0.6, 3)),
        wave(75, g("piston", 8, 1.2), g("cog", 10, 0.5, 3)),
        wave(100, g("warlord", 3, 2), g("piston", 6, 1.3, 3), g("stormbird", 6, 0.7, 5)),
      ],
      startingCredits: 550,
      reactorEnergy: 20,
      hpGrowth: 0.4,
    },
    {
      id: "planetenrad",
      name: "Planetenrad",
      focus: "Nur Kernsortiment und Kontrolle: Impuls, Nova, Kryo, Flak, Tesla, Gravitron, Lanze, Fokus und Zerfall",
      map: PLANETENRAD,
      circle: { interval: 18, limit: 36, earlyBonus: 3 },
      waves: [
        wave(30, g("drone", 14, 0.7)),
        wave(35, g("cog", 10, 0.9), g("glider", 6, 0.7, 4)),
        wave(40, g("piston", 6, 1.4), g("runner", 12, 0.5, 3)),
        wave(45, g("skater", 8, 0.7), g("moth", 6, 0.7, 3)),
        wave(50, g("tank", 6, 1.4), g("cog", 8, 0.7, 3)),
        wave(55, g("aegis", 6, 1.1), g("stormbird", 6, 0.8, 3)),
        wave(60, g("piston", 8, 1.2), g("splitter", 6, 1, 3)),
        wave(65, g("berserker", 5, 1.3), g("cog", 10, 0.6, 3)),
        wave(70, g("bulwark", 5, 1.3), g("glider", 8, 0.6, 3)),
        wave(75, g("piston", 10, 1.1), g("cog", 12, 0.5, 4)),
        wave(100, g("boss", 1, 1), g("piston", 8, 1.1, 4), g("stormbird", 8, 0.7, 5)),
      ],
      startingCredits: 600,
      reactorEnergy: 20,
      hpGrowth: 0.4,
      availableTowers: ["pulse", "blast", "frost", "flak", "tesla", "gravity", "lance", "focus", "decay"],
    },
    {
      id: "uhrwerk",
      name: "Uhrwerk",
      focus: "Der Haken faltet eine Bahn in den Ring. Zwei Bosse: Zerfall und Fokus, Kryo und Gravitron für die Zahnräder",
      map: UHRWERK,
      circle: { interval: 16, limit: 34, earlyBonus: 3 },
      waves: [
        wave(30, g("drone", 10, 0.8)),
        wave(35, g("cog", 6, 1.2), g("glider", 6, 0.7, 4)),
        wave(40, g("piston", 4, 1.6), g("runner", 8, 0.55, 3)),
        wave(45, g("moth", 8, 0.6), g("tank", 4, 1.5, 3)),
        wave(50, g("mender", 3, 1.5), g("cog", 8, 0.8, 2)),
        wave(55, g("piston", 6, 1.3), g("stormbird", 6, 0.8, 4)),
        wave(60, g("warlord", 2, 3), g("splitter", 6, 1, 2), g("glider", 8, 0.6, 4)),
        wave(65, g("berserker", 4, 1.4), g("cog", 8, 0.7, 3)),
        wave(70, g("aegis", 6, 1.1), g("piston", 6, 1.2, 3)),
        wave(75, g("bulwark", 4, 1.4), g("ashwing", 4, 1.1, 3), g("cog", 6, 0.7, 5)),
        wave(80, g("piston", 7, 1.2), g("stormbird", 5, 0.9, 3), g("cog", 6, 0.7, 6)),
        wave(120, g("boss", 2, 4), g("piston", 6, 1.2, 3), g("cog", 8, 0.6, 7)),
      ],
      startingCredits: 600,
      reactorEnergy: 20,
      hpGrowth: 0.4,
    },
  ],
};
