import type { MissionSector } from "../../core/types";
import { parseMap } from "../maps";
import { g, wave } from "../waves";
// Sector IX, Mondsee: ring maps on a tidal lake. Flyers and shelled swimmers keep circling,
// so they grow fast or tough with every lap.
// L-shaped ring: the wide arm of the L runs two rows from both its legs.
const EBBE = parseMap("ebbe", "Ebb", [
  "....................",
  ".S========..........",
  ".=.......=..........",
  ".=.......=..........",
  ".=.......=..........",
  ".=.......==========.",
  ".=................=.",
  ".=................=.",
  ".=................=.",
  ".==================.",
  "....................",
], "tide");
// A one-cell notch between two legs: one tower covers both.
const FLUTRING = parseMap("flutring", "Tide Ring", [
  "....................",
  ".S=======.=========.",
  ".=......=.=.......=.",
  ".=......=.=.......=.",
  ".=......=.=.......=.",
  ".=......=.=.......=.",
  ".=......=.=.......=.",
  ".=......===.......=.",
  ".=................=.",
  ".==================.",
  "....................",
], "tide");
// A long snake ring: two parallel runs in the middle sit two rows apart.
const BRANDUNG = parseMap("brandung", "Surf", [
  "......................",
  ".S===================.",
  ".=..................=.",
  ".=..................=.",
  ".=...================.",
  ".=...=................",
  ".=...=................",
  ".=...================.",
  ".=..................=.",
  ".=..................=.",
  ".====================.",
  "......................",
], "tide");
// A plus-shaped ring with narrow arms: every arm cell reaches two legs.
const SPRINGFLUT = parseMap("springflut", "Spring Tide", [
  "....................",
  "........=S==........",
  "........=..=........",
  "........=..=........",
  "...======..======...",
  "...=............=...",
  "...=............=...",
  "...=............=...",
  "...=............=...",
  "...======..======...",
  "........=..=........",
  "........=..=........",
  "........====........",
  "....................",
], "tide");
// An H-shaped ring: the corridor legs sit two rows apart between two deep notches.
const MONDFINSTERNIS = parseMap("mondfinsternis", "Lunar Eclipse", [
  "....................",
  ".S=====......======.",
  ".=....=......=....=.",
  ".=....=......=....=.",
  ".=....=......=....=.",
  ".=....========....=.",
  ".=................=.",
  ".=....========....=.",
  ".=....=......=....=.",
  ".=....=......=....=.",
  ".=....=......=....=.",
  ".======......======.",
  "....................",
], "tide");
export const MONDSEE: MissionSector = {
  id: "tide",
  name: "Moon Lake",
  missions: [
    {
      id: "ebbe",
      name: "Ebb",
      focus: "Spray Wings get tougher with every lap. Flak and Tesla clear them in the first",
      map: EBBE,
      circle: { interval: 18, limit: 45, earlyBonus: 3 },
      waves: [
        wave(30, g("drone", 10, 0.8)),
        wave(35, g("tidewing", 6, 0.8), g("drone", 8, 0.6, 3)),
        wave(40, g("runner", 14, 0.5)),
        wave(45, g("tidewing", 10, 0.6), g("tank", 3, 1.8, 3)),
        wave(50, g("glider", 8, 0.6), g("tidewing", 8, 0.6, 4)),
        wave(55, g("tank", 6, 1.4), g("drone", 14, 0.4, 3)),
        wave(55, g("tidewing", 14, 0.5), g("runner", 10, 0.5, 3)),
        wave(60, g("splitter", 8, 1), g("tidewing", 10, 0.5, 4)),
        wave(65, g("tank", 8, 1.2), g("tidewing", 12, 0.5, 3)),
        wave(70, g("tidewing", 18, 0.4), g("runner", 16, 0.4, 3)),
        wave(100, g("boss", 1, 1), g("tidewing", 14, 0.5, 4), g("tank", 6, 1.2, 6)),
      ],
      startingCredits: 550,
      reactorEnergy: 20,
      hpGrowth: 0.35,
    },
    {
      id: "flutring",
      name: "Tide Ring",
      focus: "Nautilus gains momentum with every lap. Jammer, Gravitron and Decay slow it",
      map: FLUTRING,
      circle: { interval: 17, limit: 42, earlyBonus: 3 },
      waves: [
        wave(30, g("drone", 12, 0.7)),
        wave(35, g("nautilus", 2, 3), g("drone", 8, 0.6, 3)),
        wave(40, g("runner", 12, 0.5), g("tidewing", 5, 0.7, 4)),
        wave(45, g("nautilus", 3, 2.2), g("glider", 6, 0.7, 3)),
        wave(50, g("tank", 5, 1.4), g("tidewing", 6, 0.6, 3)),
        wave(55, g("nautilus", 3, 2), g("runner", 10, 0.45, 3)),
        wave(55, g("splitter", 6, 1), g("tidewing", 8, 0.5, 4)),
        wave(60, g("nautilus", 4, 1.8), g("drone", 14, 0.35, 2)),
        wave(65, g("aegis", 6, 1), g("tidewing", 10, 0.5, 3)),
        wave(70, g("nautilus", 5, 1.6), g("skater", 8, 0.5, 3)),
        wave(100, g("boss", 1, 1), g("nautilus", 4, 1.8, 4), g("tidewing", 10, 0.5, 6)),
      ],
      startingCredits: 570,
      reactorEnergy: 20,
      hpGrowth: 0.38,
    },
    {
      id: "brandung",
      name: "Surf",
      focus: "Long serpentine ring, the middle lanes lie close. Cryo slows, Decay clears the tanks",
      map: BRANDUNG,
      circle: { interval: 16, limit: 45, earlyBonus: 3 },
      waves: [
        wave(30, g("drone", 8, 0.7)),
        wave(35, g("tidewing", 6, 0.6), g("runner", 4, 0.5, 3)),
        wave(40, g("nautilus", 2, 2), g("drone", 8, 0.5, 3)),
        wave(45, g("mender", 3, 1.5), g("drone", 10, 0.45, 2)),
        wave(50, g("tank", 6, 1.3), g("tidewing", 8, 0.5, 4)),
        wave(55, g("nautilus", 4, 1.8), g("glider", 8, 0.5, 3)),
        wave(55, g("splitter", 8, 0.8), g("runner", 10, 0.4, 3)),
        wave(60, g("aegis", 5, 1), g("tidewing", 8, 0.45, 3)),
        wave(65, g("nautilus", 4, 1.5), g("skater", 6, 0.5, 3)),
        wave(70, g("bulwark", 3, 1.4), g("tidewing", 10, 0.4, 3)),
        wave(75, g("nautilus", 5, 1.3), g("berserker", 3, 1.3, 4)),
        wave(110, g("boss", 2, 3), g("tidewing", 8, 0.4, 4), g("runner", 8, 0.4, 8)),
      ],
      startingCredits: 600,
      reactorEnergy: 20,
      hpGrowth: 0.4,
    },
    {
      id: "springflut",
      name: "Spring Tide",
      focus: "Short interval and tight limit. The cross center bundles all arms, calling early pays off",
      map: SPRINGFLUT,
      circle: { interval: 14, limit: 35, earlyBonus: 4 },
      waves: [
        wave(30, g("drone", 10, 0.7)),
        wave(35, g("tidewing", 6, 0.6), g("runner", 6, 0.5, 3)),
        wave(40, g("nautilus", 2, 2), g("glider", 6, 0.6, 3)),
        wave(45, g("tank", 4, 1.3), g("tidewing", 8, 0.5, 3)),
        wave(50, g("splitter", 6, 0.9), g("nautilus", 3, 1.8, 4)),
        wave(55, g("tidewing", 12, 0.4), g("runner", 10, 0.4, 3)),
        wave(55, g("mender", 3, 1.4), g("drone", 14, 0.35, 2)),
        wave(60, g("nautilus", 5, 1.4), g("skater", 8, 0.5, 3)),
        wave(65, g("aegis", 6, 1), g("tidewing", 12, 0.4, 3)),
        wave(70, g("bulwark", 4, 1.4), g("tidewing", 14, 0.4, 3)),
        wave(75, g("warlord", 2, 3), g("nautilus", 6, 1.3, 3)),
        wave(110, g("boss", 2, 3), g("tidewing", 12, 0.4, 4), g("runner", 12, 0.4, 8)),
      ],
      startingCredits: 620,
      reactorEnergy: 20,
      hpGrowth: 0.4,
    },
    {
      id: "mondfinsternis",
      name: "Lunar Eclipse",
      focus: "Two deep bays, the middle lanes lie close together. Gravitron and Jammer slow the echo, three bosses at the end",
      map: MONDFINSTERNIS,
      circle: { interval: 16, limit: 40, earlyBonus: 4 },
      waves: [
        wave(30, g("drone", 10, 0.7)),
        wave(35, g("tidewing", 8, 0.5), g("runner", 6, 0.5, 3)),
        wave(40, g("nautilus", 3, 1.8), g("glider", 6, 0.6, 3)),
        wave(45, g("tank", 6, 1.2), g("tidewing", 8, 0.5, 3)),
        wave(50, g("splitter", 8, 0.8), g("nautilus", 3, 1.6, 4)),
        wave(55, g("aegis", 5, 1), g("tidewing", 8, 0.45, 3)),
        wave(60, g("nautilus", 5, 1.4), g("berserker", 4, 1.3, 4)),
        wave(65, g("bulwark", 4, 1.4), g("tidewing", 10, 0.4, 3)),
        wave(70, g("warlord", 2, 3), g("nautilus", 5, 1.3, 3)),
        wave(75, g("tidewing", 10, 0.35), g("skater", 6, 0.5, 3)),
        wave(80, g("nautilus", 6, 1.2), g("tank", 5, 1.2, 4)),
        { ...wave(85, g("nautilus", 3, 2.5), g("piston", 2, 2.5, 4)), hpMultiplier: 6 },
        wave(140, g("boss", 3, 3), g("nautilus", 4, 1.4, 4), g("tidewing", 6, 0.4, 6)),
      ],
      startingCredits: 650,
      reactorEnergy: 20,
      hpGrowth: 0.5,
    },
  ],
};
