import type { EnemyDefinition, EnemyId } from "../core/types";
export const ENEMY_CONTENT = {
  drone: {
    id: "drone",
    name: "Drohne",
    hp: 55,
    speed: 1.45,
    reward: 9,
    leak: 1,
    color: 0xf0cf87,
    size: 0.19,
    layer: "ground",
    visual: { shape: "polygon", sides: 4 },
  },
  runner: {
    id: "runner",
    name: "Sprinter",
    hp: 40,
    speed: 2.35,
    reward: 10,
    leak: 1,
    color: 0xff947d,
    size: 0.16,
    layer: "ground",
    visual: { shape: "polygon", sides: 3 },
  },
  tank: {
    id: "tank",
    name: "Panzer",
    hp: 210,
    speed: 0.95,
    reward: 20,
    leak: 2,
    color: 0xea9bda,
    size: 0.27,
    layer: "ground",
    visual: { shape: "polygon", sides: 4, rotation: Math.PI / 4 },
  },
  boss: {
    id: "boss",
    name: "Titan",
    hp: 1600,
    speed: 0.65,
    reward: 100,
    leak: 10,
    color: 0xff647c,
    size: 0.38,
    layer: "ground",
    visual: { shape: "polygon", sides: 8 },
  },
  glider: {
    id: "glider",
    name: "Gleiter",
    hp: 45,
    speed: 1.9,
    reward: 11,
    leak: 1,
    color: 0xbfe9ff,
    size: 0.18,
    layer: "air",
    visual: { shape: "glider" },
  },
  // --- Trait enemies, introduced from Sektor II on ---
  // Eisläufer: schneller Läufer, immun gegen Verlangsamung, Glut statt Kryo.
  skater: {
    id: "skater",
    name: "Eisläufer",
    hp: 50,
    speed: 1.8,
    reward: 11,
    leak: 1,
    color: 0x9fe6ff,
    size: 0.17,
    layer: "ground",
    visual: { shape: "polygon", sides: 3, rotation: Math.PI },
    traits: [{ kind: "slowImmune" }, { kind: "swift", speed: 0.35, hp: 0.2 }],
  },
  // Splitter: zerfällt beim Tod in Drohnen, Lanzen auf den Geraden.
  splitter: {
    id: "splitter",
    name: "Splitter",
    hp: 120,
    speed: 1.1,
    reward: 12,
    leak: 2,
    color: 0xc6b4ff,
    size: 0.24,
    layer: "ground",
    visual: { shape: "polygon", sides: 6 },
    traits: [{ kind: "splitOnDeath", type: "drone", count: 3 }],
  },
  // Skarabäus: gepanzerter Läufer, Wucht und Fallen statt Streufeuer.
  scarab: {
    id: "scarab",
    name: "Skarabäus",
    hp: 80,
    speed: 1.5,
    reward: 14,
    leak: 1,
    color: 0xd9a441,
    size: 0.2,
    layer: "ground",
    visual: { shape: "polygon", sides: 6, rotation: Math.PI / 6 },
    traits: [{ kind: "armor", reduction: 0.3 }, { kind: "swift", speed: 0.3, hp: 0.15 }],
  },
  // Gräber: taucht ab, nur Fallen und Flächenschaden treffen ihn unter der Erde.
  burrower: {
    id: "burrower",
    name: "Gräber",
    hp: 140,
    speed: 1.05,
    reward: 16,
    leak: 2,
    color: 0xb98a52,
    size: 0.24,
    layer: "ground",
    visual: { shape: "polygon", sides: 5, rotation: Math.PI / 2 },
    traits: [{ kind: "burrow", every: 3, length: 1.2 }],
  },
  // Böenläufer: rast in kurzen Schüben, wer ihn trifft, muss das Tempo vorhalten.
  gale: {
    id: "gale",
    name: "Böenläufer",
    hp: 110,
    speed: 1.2,
    reward: 14,
    leak: 1,
    color: 0x9fd8ff,
    size: 0.21,
    layer: "ground",
    visual: { shape: "polygon", sides: 3, rotation: Math.PI },
    traits: [{ kind: "surge", every: 4, length: 1, factor: 2.2 }],
  },
  // Sturmvogel: schneller Flieger mit Schild, Flak und Impuls müssen ihn schnell brechen.
  stormbird: {
    id: "stormbird",
    name: "Sturmvogel",
    hp: 70,
    speed: 1.6,
    reward: 15,
    leak: 1,
    color: 0xc8e8ff,
    size: 0.2,
    layer: "air",
    visual: { shape: "glider" },
    traits: [{ kind: "shield", capacity: 0.5, delay: 2.5 }, { kind: "swift", speed: 0.2, hp: 0.1 }],
  },
  // Schwarmameise: schwach allein, im Rudel kaum zu knacken; Flächenschaden lohnt.
  ant: {
    id: "ant",
    name: "Schwarmameise",
    hp: 45,
    speed: 1.35,
    reward: 7,
    leak: 1,
    color: 0xb6ff6a,
    size: 0.15,
    layer: "ground",
    visual: { shape: "polygon", sides: 6 },
    traits: [{ kind: "swarm", radius: 1.0, per: 0.1, max: 0.5 }],
  },
  // Urwaldkoloss: gepanzert und regenerierend, braucht Wucht statt Dauerfeuer.
  colossus: {
    id: "colossus",
    name: "Urwaldkoloss",
    hp: 420,
    speed: 0.7,
    reward: 40,
    leak: 3,
    color: 0x4f9a3a,
    size: 0.34,
    layer: "ground",
    visual: { shape: "polygon", sides: 8, rotation: Math.PI / 8 },
    traits: [{ kind: "armor", reduction: 0.25 }, { kind: "regen", percent: 0.015 }],
  },
  // Panzerkrebs: wird mit jeder Wunde zäher, Burst und Zerfall schlagen Dauerfeuer.
  crab: {
    id: "crab",
    name: "Panzerkrebs",
    hp: 260,
    speed: 0.8,
    reward: 24,
    leak: 2,
    color: 0xff7a5c,
    size: 0.28,
    layer: "ground",
    visual: { shape: "polygon", sides: 8 },
    traits: [{ kind: "harden", max: 0.6 }],
  },
  // Qualle: schwebender Heiler, Flak holt sie herunter.
  jelly: {
    id: "jelly",
    name: "Qualle",
    hp: 90,
    speed: 1.2,
    reward: 15,
    leak: 1,
    color: 0x7af0e0,
    size: 0.22,
    layer: "air",
    visual: { shape: "polygon", sides: 7, tentacles: 5 },
    traits: [{ kind: "healer", radius: 1.4, percent: 0.03 }],
  },
  // Schleimer: regeneriert, Burst-Schaden schlägt Dauerfeuer.
  slime: {
    id: "slime",
    name: "Schleimer",
    hp: 150,
    speed: 1.0,
    reward: 15,
    leak: 2,
    color: 0xa6d65a,
    size: 0.25,
    layer: "ground",
    visual: { shape: "polygon", sides: 7 },
    traits: [{ kind: "regen", percent: 0.02 }],
  },
  // Sanitäter: heilt Umstehende, zuerst töten.
  mender: {
    id: "mender",
    name: "Sanitäter",
    hp: 90,
    speed: 1.15,
    reward: 16,
    leak: 1,
    color: 0x7dffb0,
    size: 0.21,
    layer: "ground",
    visual: { shape: "polygon", sides: 5 },
    traits: [{ kind: "healer", radius: 1.5, percent: 0.04 }],
  },
  // Schildträger: Schild regeneriert nach kurzer Pause.
  aegis: {
    id: "aegis",
    name: "Schildträger",
    hp: 85,
    speed: 1.15,
    reward: 16,
    leak: 2,
    color: 0x8fa8ff,
    size: 0.24,
    layer: "ground",
    visual: { shape: "polygon", sides: 6, rotation: Math.PI / 6 },
    traits: [{ kind: "shield", capacity: 0.6, delay: 3 }],
  },
  // Phantom: getarnt, nur mit Detektor angreifbar.
  phantom: {
    id: "phantom",
    name: "Phantom",
    hp: 65,
    speed: 1.6,
    reward: 14,
    leak: 1,
    color: 0xd0d6ff,
    size: 0.18,
    layer: "ground",
    visual: { shape: "polygon", sides: 3 },
    traits: [{ kind: "stealth" }],
  },
  // Bollwerk: schwere Rüstung, braucht Wucht statt Streufeuer.
  bulwark: {
    id: "bulwark",
    name: "Bollwerk",
    hp: 200,
    speed: 0.85,
    reward: 26,
    leak: 2,
    color: 0xb0b8c0,
    size: 0.3,
    layer: "ground",
    visual: { shape: "polygon", sides: 4 },
    traits: [{ kind: "armor", reduction: 0.35 }],
  },
  // Kommandant: stärkt Gegner in der Nähe.
  warlord: {
    id: "warlord",
    name: "Kommandant",
    hp: 240,
    speed: 0.8,
    reward: 36,
    leak: 3,
    color: 0xe0a84f,
    size: 0.3,
    layer: "ground",
    visual: { shape: "polygon", sides: 5, rotation: Math.PI },
    traits: [{ kind: "leader", radius: 1.6, speed: 0.2, resist: 0.15 }],
  },
  // Phasenläufer: weicht periodisch Treffern aus.
  blinker: {
    id: "blinker",
    name: "Phasenläufer",
    hp: 70,
    speed: 1.7,
    reward: 13,
    leak: 1,
    color: 0xff7de9,
    size: 0.17,
    layer: "ground",
    visual: { shape: "polygon", sides: 4, rotation: Math.PI / 4 },
    traits: [{ kind: "evade", every: 3 }],
  },
  // Berserker: nicht aufzuhalten, sprintet bei halber Gesundheit.
  berserker: {
    id: "berserker",
    name: "Berserker",
    hp: 240,
    speed: 1.0,
    reward: 25,
    leak: 2,
    color: 0xff5a3d,
    size: 0.28,
    layer: "ground",
    visual: { shape: "polygon", sides: 6 },
    traits: [{ kind: "unstoppable" }, { kind: "sprint", threshold: 0.5, factor: 1.7, duration: 2.5 }],
  },
} satisfies Record<string, EnemyDefinition>;
export const ENEMIES: Readonly<Record<EnemyId, Readonly<EnemyDefinition>>> =
  ENEMY_CONTENT;
