import type { EnemyDefinition, EnemyId } from "../core/types";
export const ENEMY_CONTENT = {
  drone: {
    id: "drone",
    name: "Drone",
    hp: 55,
    speed: 1.45,
    reward: 9,
    leak: 1,
    color: 0xf0cf87,
    size: 0.19,
    layer: "ground",
    visual: { shape: "polygon", sides: 4 },
  },
  runner: {
    id: "runner",
    name: "Sprinter",
    hp: 40,
    speed: 2.35,
    reward: 10,
    leak: 1,
    color: 0xff947d,
    size: 0.16,
    layer: "ground",
    visual: { shape: "polygon", sides: 3 },
  },
  tank: {
    id: "tank",
    name: "Tank",
    hp: 210,
    speed: 0.95,
    reward: 20,
    leak: 2,
    color: 0xea9bda,
    size: 0.27,
    layer: "ground",
    visual: { shape: "polygon", sides: 4, rotation: Math.PI / 4 },
  },
  boss: {
    id: "boss",
    name: "Titan",
    hp: 1600,
    speed: 0.65,
    reward: 100,
    leak: 10,
    color: 0xff647c,
    size: 0.38,
    layer: "ground",
    visual: { shape: "polygon", sides: 8 },
  },
  glider: {
    id: "glider",
    name: "Glider",
    hp: 45,
    speed: 1.9,
    reward: 11,
    leak: 1,
    color: 0xbfe9ff,
    size: 0.18,
    layer: "air",
    visual: { shape: "glider" },
  },
  // --- Trait enemies, introduced from Sector II on ---
  // Ice Strider: fast runner, immune to slow; Ember instead of Cryo.
  skater: {
    id: "skater",
    name: "Ice Strider",
    hp: 50,
    speed: 1.8,
    reward: 11,
    leak: 1,
    color: 0x9fe6ff,
    size: 0.17,
    layer: "ground",
    visual: { shape: "polygon", sides: 3, rotation: Math.PI },
    traits: [{ kind: "slowImmune" }, { kind: "swift", speed: 0.35, hp: 0.2 }],
  },
  // Shard: splits into Drones on death; Lances on the straights.
  splitter: {
    id: "splitter",
    name: "Shard",
    hp: 120,
    speed: 1.1,
    reward: 12,
    leak: 2,
    color: 0xc6b4ff,
    size: 0.24,
    layer: "ground",
    visual: { shape: "polygon", sides: 6 },
    traits: [{ kind: "splitOnDeath", type: "drone", count: 3 }],
  },
  // Scarab: armored runner; heavy hits and traps instead of spray fire.
  scarab: {
    id: "scarab",
    name: "Scarab",
    hp: 80,
    speed: 1.5,
    reward: 14,
    leak: 1,
    color: 0xd9a441,
    size: 0.2,
    layer: "ground",
    visual: { shape: "polygon", sides: 6, rotation: Math.PI / 6 },
    traits: [{ kind: "armor", reduction: 0.3 }, { kind: "swift", speed: 0.3, hp: 0.15 }],
  },
  // Burrower: dives underground; only traps and area damage hit it there.
  burrower: {
    id: "burrower",
    name: "Burrower",
    hp: 140,
    speed: 1.05,
    reward: 16,
    leak: 2,
    color: 0xb98a52,
    size: 0.24,
    layer: "ground",
    visual: { shape: "polygon", sides: 5, rotation: Math.PI / 2 },
    traits: [{ kind: "burrow", every: 3, length: 1.2 }],
  },
  // Gust Runner: dashes in short bursts; whoever shoots it must lead the target.
  gale: {
    id: "gale",
    name: "Gust Runner",
    hp: 110,
    speed: 1.2,
    reward: 14,
    leak: 1,
    color: 0x9fd8ff,
    size: 0.21,
    layer: "ground",
    visual: { shape: "polygon", sides: 3, rotation: Math.PI },
    traits: [{ kind: "surge", every: 4, length: 1, factor: 2.2 }],
  },
  // Stormbird: fast shielded flyer; Flak and Pulse must break it quickly.
  stormbird: {
    id: "stormbird",
    name: "Stormbird",
    hp: 70,
    speed: 1.6,
    reward: 15,
    leak: 1,
    color: 0xc8e8ff,
    size: 0.2,
    layer: "air",
    visual: { shape: "glider" },
    traits: [{ kind: "shield", capacity: 0.5, delay: 2.5 }, { kind: "swift", speed: 0.2, hp: 0.1 }],
  },
  // Swarm Ant: weak alone, hard to crack as a pack; area damage pays off.
  ant: {
    id: "ant",
    name: "Swarm Ant",
    hp: 45,
    speed: 1.35,
    reward: 7,
    leak: 1,
    color: 0xb6ff6a,
    size: 0.15,
    layer: "ground",
    visual: { shape: "polygon", sides: 6 },
    traits: [{ kind: "swarm", radius: 1.0, per: 0.1, max: 0.5 }],
  },
  // Jungle Colossus: armored and regenerating; needs heavy hits instead of sustained fire.
  colossus: {
    id: "colossus",
    name: "Jungle Colossus",
    hp: 420,
    speed: 0.7,
    reward: 40,
    leak: 3,
    color: 0x4f9a3a,
    size: 0.34,
    layer: "ground",
    visual: { shape: "polygon", sides: 8, rotation: Math.PI / 8 },
    traits: [{ kind: "armor", reduction: 0.25 }, { kind: "regen", percent: 0.015 }],
  },
  // Armor Crab: toughens with every wound; Burst and Decay beat sustained fire.
  crab: {
    id: "crab",
    name: "Armor Crab",
    hp: 260,
    speed: 0.8,
    reward: 24,
    leak: 2,
    color: 0xff7a5c,
    size: 0.28,
    layer: "ground",
    visual: { shape: "polygon", sides: 8 },
    traits: [{ kind: "harden", max: 0.6 }],
  },
  // Ember Runner: speeds up as HP drops; Frost, Stasis, Tar Pit and Executioner slow or finish it.
  ember: {
    id: "ember",
    name: "Ember Runner",
    hp: 100,
    speed: 1.2,
    reward: 15,
    leak: 1,
    color: 0xff6a2a,
    size: 0.2,
    layer: "ground",
    visual: { shape: "polygon", sides: 5, rotation: -Math.PI / 2 },
    traits: [{ kind: "rage", max: 1.0 }],
  },
  // Ash Wing: armored flyer, immune to slow; Flak and Tesla bring it down.
  ashwing: {
    id: "ashwing",
    name: "Ash Wing",
    hp: 130,
    speed: 1.0,
    reward: 18,
    leak: 2,
    color: 0xb8b2ac,
    size: 0.24,
    layer: "air",
    visual: { shape: "polygon", sides: 4, rotation: Math.PI / 4 },
    traits: [{ kind: "armor", reduction: 0.25 }, { kind: "slowImmune" }],
  },
  // Crystal Warden: hardens against hits in a rhythm, burn works in full; Frost and Tar Pit keep it in range longer.
  golem: {
    id: "golem",
    name: "Crystal Warden",
    hp: 320,
    speed: 0.8,
    reward: 28,
    leak: 2,
    color: 0x5ef2e0,
    size: 0.29,
    layer: "ground",
    visual: { shape: "polygon", sides: 6, rotation: Math.PI / 6 },
    traits: [{ kind: "facet", every: 4, length: 2, reduction: 0.7 }],
  },
  // Shard Moth: fast flyer, splits into two Gliders; Flak and Tesla clear the swarms.
  moth: {
    id: "moth",
    name: "Shard Moth",
    hp: 70,
    speed: 1.45,
    reward: 12,
    leak: 1,
    color: 0xc79cf5,
    size: 0.2,
    layer: "air",
    visual: { shape: "polygon", sides: 3, rotation: 0 },
    traits: [{ kind: "splitOnDeath", type: "glider", count: 2 }],
  },
  // Airship: heavily armored flyer, drops Gliders when it crashes; upgraded Flak and Tesla bring it down.
  airship: {
    id: "airship",
    name: "Airship",
    hp: 300,
    speed: 0.75,
    reward: 30,
    leak: 2,
    color: 0x8fa3b8,
    size: 0.32,
    layer: "air",
    visual: { shape: "polygon", sides: 6, rotation: 0 },
    traits: [{ kind: "armor", reduction: 0.2 }, { kind: "splitOnDeath", type: "glider", count: 3 }],
  },
  // Jellyfish: hovering healer; Flak brings it down.
  jelly: {
    id: "jelly",
    name: "Jellyfish",
    hp: 90,
    speed: 1.2,
    reward: 15,
    leak: 1,
    color: 0x7af0e0,
    size: 0.22,
    layer: "air",
    visual: { shape: "polygon", sides: 7, tentacles: 5 },
    traits: [{ kind: "healer", radius: 1.4, percent: 0.03 }],
  },
  // Sludge: regenerates; Burst damage beats sustained fire.
  slime: {
    id: "slime",
    name: "Sludge",
    hp: 150,
    speed: 1.0,
    reward: 15,
    leak: 2,
    color: 0xa6d65a,
    size: 0.25,
    layer: "ground",
    visual: { shape: "polygon", sides: 7 },
    traits: [{ kind: "regen", percent: 0.02 }],
  },
  // Medic: heals bystanders, kill first.
  mender: {
    id: "mender",
    name: "Medic",
    hp: 90,
    speed: 1.15,
    reward: 16,
    leak: 1,
    color: 0x7dffb0,
    size: 0.21,
    layer: "ground",
    visual: { shape: "polygon", sides: 5 },
    traits: [{ kind: "healer", radius: 1.5, percent: 0.04 }],
  },
  // Shield Bearer: shield regenerates after a short pause.
  aegis: {
    id: "aegis",
    name: "Shield Bearer",
    hp: 85,
    speed: 1.15,
    reward: 16,
    leak: 2,
    color: 0x8fa8ff,
    size: 0.24,
    layer: "ground",
    visual: { shape: "polygon", sides: 6, rotation: Math.PI / 6 },
    traits: [{ kind: "shield", capacity: 0.6, delay: 3 }],
  },
  // Phantom: stealthed, can only be attacked with a Detector.
  phantom: {
    id: "phantom",
    name: "Phantom",
    hp: 65,
    speed: 1.6,
    reward: 14,
    leak: 1,
    color: 0xd0d6ff,
    size: 0.18,
    layer: "ground",
    visual: { shape: "polygon", sides: 3 },
    traits: [{ kind: "stealth" }],
  },
  // Bulwark: heavy armor, needs heavy hits instead of spray fire.
  bulwark: {
    id: "bulwark",
    name: "Bulwark",
    hp: 200,
    speed: 0.85,
    reward: 26,
    leak: 2,
    color: 0xb0b8c0,
    size: 0.3,
    layer: "ground",
    visual: { shape: "polygon", sides: 4 },
    traits: [{ kind: "armor", reduction: 0.35 }],
  },
  // Commander: strengthens nearby enemies.
  warlord: {
    id: "warlord",
    name: "Commander",
    hp: 240,
    speed: 0.8,
    reward: 36,
    leak: 3,
    color: 0xe0a84f,
    size: 0.3,
    layer: "ground",
    visual: { shape: "polygon", sides: 5, rotation: Math.PI },
    traits: [{ kind: "leader", radius: 1.6, speed: 0.2, resist: 0.15 }],
  },
  // Phase Runner: periodically dodges hits.
  blinker: {
    id: "blinker",
    name: "Phase Runner",
    hp: 70,
    speed: 1.7,
    reward: 13,
    leak: 1,
    color: 0xff7de9,
    size: 0.17,
    layer: "ground",
    visual: { shape: "polygon", sides: 4, rotation: Math.PI / 4 },
    traits: [{ kind: "evade", every: 3 }],
  },
  // Berserker: unstoppable, sprints at half health.
  berserker: {
    id: "berserker",
    name: "Berserker",
    hp: 240,
    speed: 1.0,
    reward: 25,
    leak: 2,
    color: 0xff5a3d,
    size: 0.28,
    layer: "ground",
    visual: { shape: "polygon", sides: 6 },
    traits: [{ kind: "unstoppable" }, { kind: "sprint", threshold: 0.5, factor: 1.7, duration: 2.5 }],
  },
  // Leap Spider: periodically leaps into the air; Pulse, Tesla and Lance hit both layers.
  leaper: {
    id: "leaper",
    name: "Leap Spider",
    hp: 95,
    speed: 1.35,
    reward: 16,
    leak: 1,
    color: 0x9be15d,
    size: 0.2,
    layer: "ground",
    visual: { shape: "star", points: 8, inner: 0.45 },
    traits: [{ kind: "leap", every: 3, length: 1 }],
  },
  // Diver: flyer that dives to the ground; Pulse, Tesla and Shrapnel always hit it.
  skimmer: {
    id: "skimmer",
    name: "Diver",
    hp: 85,
    speed: 1.5,
    reward: 16,
    leak: 1,
    color: 0x4fd1ff,
    size: 0.21,
    layer: "air",
    visual: { shape: "glider" },
    traits: [
      { kind: "leap", every: 4, length: 1.5 },
      { kind: "swift", speed: 0.2, hp: 0.1 },
    ],
  },
  // Damper: makes itself and its neighbors immune to control; Lance, Focus or Jammer.
  warden: {
    id: "warden",
    name: "Damper",
    hp: 170,
    speed: 0.95,
    reward: 24,
    leak: 2,
    color: 0x8a7dff,
    size: 0.26,
    layer: "ground",
    visual: { shape: "orb", moons: 3 },
    traits: [{ kind: "dampen", radius: 1.6 }],
  },
  // Broodmother: armored, lays Swarm Ants along the way; Focus, Lance, Decay; Jammer stops the brood.
  broodmother: {
    id: "broodmother",
    name: "Broodmother",
    hp: 400,
    speed: 0.72,
    reward: 36,
    leak: 3,
    color: 0xc2a14a,
    size: 0.34,
    layer: "ground",
    visual: { shape: "polygon", sides: 7, tentacles: 6 },
    traits: [
      { kind: "brood", type: "ant", every: 2.5, max: 4 },
      { kind: "armor", reduction: 0.15 },
    ],
  },
  // Spark Worm: disables nearby towers on death; Lance, Mortar or traps far from the towers.
  sparkworm: {
    id: "sparkworm",
    name: "Spark Worm",
    hp: 210,
    speed: 1.0,
    reward: 22,
    leak: 2,
    color: 0xffe14d,
    size: 0.27,
    layer: "ground",
    visual: { shape: "worm", segments: 5 },
    traits: [{ kind: "overload", radius: 1.8, cycles: 2 }],
  },
  // Molter: armored at first, fast below half health; Decay and Focus, then Cryo.
  molter: {
    id: "molter",
    name: "Molter",
    hp: 240,
    speed: 0.85,
    reward: 24,
    leak: 2,
    color: 0xd96b8a,
    size: 0.28,
    layer: "ground",
    visual: { shape: "polygon", sides: 6, rotation: 0.5 },
    traits: [{ kind: "molt", threshold: 0.5, armor: 0.5, speed: 1.8 }],
  },
  // Will-o'-Wisp: stealthed flyer that dodges hits; Detector with Flak or Tesla, Ember.
  wisp: {
    id: "wisp",
    name: "Will-o'-Wisp",
    hp: 60,
    speed: 1.55,
    reward: 15,
    leak: 1,
    color: 0xb8fff4,
    size: 0.18,
    layer: "air",
    visual: { shape: "orb", moons: 0 },
    traits: [{ kind: "stealth" }, { kind: "evade", every: 4 }],
  },
  // Hydra: regenerates and splits into two Hydra Heads; Jammer, Nova, Quake.
  hydra: {
    id: "hydra",
    name: "Hydra",
    hp: 280,
    speed: 0.85,
    reward: 28,
    leak: 2,
    color: 0x2fbf8f,
    size: 0.3,
    layer: "ground",
    visual: { shape: "polygon", sides: 5, tentacles: 3 },
    traits: [
      { kind: "regen", percent: 0.012 },
      { kind: "splitOnDeath", type: "hydraling", count: 2 },
    ],
  },
  // Hydra Head: fragment of the Hydra, speeds up when wounded; Nova, Shrapnel, Executioner.
  hydraling: {
    id: "hydraling",
    name: "Hydra Head",
    hp: 70,
    speed: 1.35,
    reward: 8,
    leak: 1,
    color: 0x5ff2b4,
    size: 0.18,
    layer: "ground",
    visual: { shape: "star", points: 5, inner: 0.55 },
    traits: [{ kind: "rage", max: 0.8 }],
  },
  // Thunder Cell: shielded flyer, disables towers on death; Flak, Tesla, Jammer.
  stormcell: {
    id: "stormcell",
    name: "Thunder Cell",
    hp: 160,
    speed: 0.85,
    reward: 26,
    leak: 2,
    color: 0x6f8bff,
    size: 0.27,
    layer: "air",
    visual: { shape: "orb", moons: 4 },
    traits: [
      { kind: "overload", radius: 1.5, cycles: 1 },
      { kind: "shield", capacity: 0.3, delay: 3 },
    ],
  },
  // Cogwheel: speeds up with every cell; Cryo, Gravitron (the pull takes its momentum) and Tesla.
  cog: {
    id: "cog",
    name: "Cogwheel",
    hp: 90,
    speed: 1.25,
    reward: 13,
    leak: 1,
    color: 0xd9a441,
    size: 0.2,
    layer: "ground",
    visual: { shape: "star", points: 8, inner: 0.7 },
    traits: [{ kind: "momentum", per: 0.03, max: 0.9 }],
  },
  // Piston Tank: armored and harder with every lap; Decay, Focus and Lance, best in the first lap.
  piston: {
    id: "piston",
    name: "Piston Tank",
    hp: 300,
    speed: 0.85,
    reward: 30,
    leak: 2,
    color: 0xb8742e,
    size: 0.3,
    layer: "ground",
    visual: { shape: "polygon", sides: 4, rotation: Math.PI / 4 },
    traits: [{ kind: "armor", reduction: 0.2 }, { kind: "lap", per: 0.15, max: 0.6 }],
  },
  // Spray Wing: fast flyer that gets harder with every lap; Flak and Tesla.
  tidewing: {
    id: "tidewing",
    name: "Spray Wing",
    hp: 85,
    speed: 1.5,
    reward: 14,
    leak: 1,
    color: 0xbcd6f0,
    size: 0.2,
    layer: "air",
    visual: { shape: "glider" },
    traits: [{ kind: "lap", per: 0.12, max: 0.48 }],
  },
  // Nautilus: shielded and with momentum; Jammer, Gravitron and Decay.
  nautilus: {
    id: "nautilus",
    name: "Nautilus",
    hp: 360,
    speed: 0.75,
    reward: 34,
    leak: 2,
    color: 0x7fa8d8,
    size: 0.31,
    layer: "ground",
    visual: { shape: "orb", moons: 0 },
    traits: [{ kind: "shield", capacity: 0.4, delay: 3 }, { kind: "momentum", per: 0.02, max: 0.8 }],
  },
  // --- New traits: not placed in any mission yet ---
  // Prism Runner: Refraction: halves instant hits; Pulse, Nova and Mortar.
  prism: {
    id: "prism",
    name: "Prism Runner",
    hp: 140,
    speed: 1.1,
    reward: 16,
    leak: 1,
    color: 0x7fd3e8,
    size: 0.22,
    layer: "ground",
    visual: { shape: "star", points: 6, inner: 0.6 },
    traits: [{ kind: "refract", factor: 0.5 }],
  },
  // Mirror Wing: Refraction in the air: halves Tesla; Flak and Pulse.
  mirrorwing: {
    id: "mirrorwing",
    name: "Mirror Wing",
    hp: 110,
    speed: 1.35,
    reward: 17,
    leak: 1,
    color: 0xb9c7ff,
    size: 0.21,
    layer: "air",
    visual: { shape: "glider" },
    traits: [{ kind: "refract", factor: 0.5 }],
  },
  // Pressure Bunker: Blastproof: area damage greatly reduced; Pulse, Focus, Lance and Corrosion.
  bunker: {
    id: "bunker",
    name: "Pressure Bunker",
    hp: 340,
    speed: 0.75,
    reward: 30,
    leak: 2,
    color: 0x8a8f7a,
    size: 0.31,
    layer: "ground",
    visual: { shape: "polygon", sides: 6, rotation: Math.PI / 2 },
    traits: [{ kind: "blastproof", reduction: 0.6 }, { kind: "armor", reduction: 0.1 }],
  },
  // Rubble Swarm: Blastproof and tough in a swarm: Tesla, Shrapnel and Caltrops.
  pebble: {
    id: "pebble",
    name: "Rubble Swarm",
    hp: 38,
    speed: 1.4,
    reward: 8,
    leak: 1,
    color: 0xc9a36b,
    size: 0.15,
    layer: "ground",
    visual: { shape: "polygon", sides: 5, rotation: 0.3 },
    traits: [{ kind: "blastproof", reduction: 0.5 }, { kind: "swarm", radius: 1, per: 0.08, max: 0.4 }],
  },
  // Insulator: Insulated: Tesla chains break off at it; Nova, Pulse and Mortar.
  insulator: {
    id: "insulator",
    name: "Insulator",
    hp: 170,
    speed: 1.0,
    reward: 18,
    leak: 2,
    color: 0xd8c24a,
    size: 0.25,
    layer: "ground",
    visual: { shape: "orb", moons: 1 },
    traits: [{ kind: "insulated" }],
  },
  // Salamander: Heat Shield: immune to burn and bleed; Pulse, Decay and Nova.
  salamander: {
    id: "salamander",
    name: "Salamander",
    hp: 150,
    speed: 1.15,
    reward: 18,
    leak: 1,
    color: 0xff7a3d,
    size: 0.22,
    layer: "ground",
    visual: { shape: "worm", segments: 3 },
    traits: [{ kind: "heatshield" }],
  },
  // Magma Moth: Heat Shield in the air: Flak and Tesla instead of Ember.
  cinderwing: {
    id: "cinderwing",
    name: "Magma Moth",
    hp: 100,
    speed: 1.4,
    reward: 16,
    leak: 1,
    color: 0xff9f5a,
    size: 0.2,
    layer: "air",
    visual: { shape: "glider" },
    traits: [{ kind: "heatshield" }],
  },
  // Monolith: Mirror Armor: each hit at most 6 % of HP; Tesla, Pulse, Ember and Executioner.
  monolith: {
    id: "monolith",
    name: "Monolith",
    hp: 520,
    speed: 0.6,
    reward: 42,
    leak: 3,
    color: 0x9aa7b8,
    size: 0.36,
    layer: "ground",
    visual: { shape: "polygon", sides: 4, rotation: Math.PI / 8 },
    traits: [{ kind: "mirror", cap: 0.06 }],
  },
  // Twin Runner: Link: shares damage with its own kind in radius; Nova, Mortar and Executioner.
  twin: {
    id: "twin",
    name: "Twin Runner",
    hp: 120,
    speed: 1.1,
    reward: 14,
    leak: 1,
    color: 0xa3e07a,
    size: 0.21,
    layer: "ground",
    visual: { shape: "orb", moons: 2 },
    traits: [{ kind: "link", radius: 1.6 }],
  },
  // Chain Jelly: Link in the air: Tesla and Flak.
  chainling: {
    id: "chainling",
    name: "Chain Jelly",
    hp: 75,
    speed: 1.35,
    reward: 13,
    leak: 1,
    color: 0x7ae0c8,
    size: 0.19,
    layer: "air",
    visual: { shape: "polygon", sides: 7, tentacles: 3 },
    traits: [{ kind: "link", radius: 1.4 }],
  },
  // Decoy: Lure: towers in radius must target it; Corrosion, Decay and Executioner.
  decoy: {
    id: "decoy",
    name: "Decoy",
    hp: 260,
    speed: 0.85,
    reward: 28,
    leak: 2,
    color: 0xe0607a,
    size: 0.29,
    layer: "ground",
    visual: { shape: "star", points: 5, inner: 0.5 },
    traits: [{ kind: "taunt", radius: 2.5 }, { kind: "armor", reduction: 0.3 }],
  },
  // Beacon Buoy: shielded lure in the air: Flak, Tesla and Jammer.
  buoy: {
    id: "buoy",
    name: "Beacon Buoy",
    hp: 160,
    speed: 0.9,
    reward: 24,
    leak: 2,
    color: 0xffd166,
    size: 0.26,
    layer: "air",
    visual: { shape: "orb", moons: 5 },
    traits: [{ kind: "taunt", radius: 2 }, { kind: "shield", capacity: 0.4, delay: 3 }],
  },
  // Martyr: Sacrifice: heals its neighbors on death; Nova, Mortar and Jammer.
  martyr: {
    id: "martyr",
    name: "Martyr",
    hp: 110,
    speed: 1.1,
    reward: 14,
    leak: 1,
    color: 0xf2e6c9,
    size: 0.21,
    layer: "ground",
    visual: { shape: "polygon", sides: 3, rotation: Math.PI / 2 },
    traits: [{ kind: "martyr", radius: 1.8, heal: 0.25 }],
  },
  // Soul Spark: Sacrifice in the air: Flak and Tesla.
  soulspark: {
    id: "soulspark",
    name: "Soul Spark",
    hp: 60,
    speed: 1.55,
    reward: 12,
    leak: 1,
    color: 0xe8d4ff,
    size: 0.17,
    layer: "air",
    visual: { shape: "star", points: 4, inner: 0.4 },
    traits: [{ kind: "martyr", radius: 1.5, heal: 0.12 }],
  },
  // Packwolf: Pack: speeds up with every neighbor; Cryo, Nova and Gravitron.
  wolf: {
    id: "wolf",
    name: "Packwolf",
    hp: 75,
    speed: 1.3,
    reward: 11,
    leak: 1,
    color: 0xb8c4d0,
    size: 0.19,
    layer: "ground",
    visual: { shape: "polygon", sides: 5, rotation: Math.PI },
    traits: [{ kind: "pack", radius: 1.5, perAlly: 0.08, max: 0.4 }],
  },
  // Storm Falcon: Pack in the air: Tesla and Flak.
  raptor: {
    id: "raptor",
    name: "Storm Falcon",
    hp: 65,
    speed: 1.6,
    reward: 12,
    leak: 1,
    color: 0xd9a066,
    size: 0.18,
    layer: "air",
    visual: { shape: "glider" },
    traits: [{ kind: "pack", radius: 1.5, perAlly: 0.1, max: 0.5 }],
  },
  // Column Runner: Pack in the slipstream: Cryo, Nova and Gravitron.
  drafter: {
    id: "drafter",
    name: "Column Runner",
    hp: 70,
    speed: 1.35,
    reward: 11,
    leak: 1,
    color: 0xa8e6ef,
    size: 0.18,
    layer: "ground",
    visual: { shape: "polygon", sides: 3, rotation: -Math.PI / 2 },
    traits: [{ kind: "pack", radius: 1.5, perAlly: 0.08, max: 0.4 }],
  },
  // Veil Weaver: Cloak Field: cloaks neighbors until a Detector reveals them; Detector, Lance and Mortar.
  veiler: {
    id: "veiler",
    name: "Veil Weaver",
    hp: 130,
    speed: 1.0,
    reward: 20,
    leak: 2,
    color: 0x8e7cc3,
    size: 0.23,
    layer: "ground",
    visual: { shape: "polygon", sides: 7, rotation: 0.2, tentacles: 2 },
    traits: [{ kind: "cloakField", radius: 1.6 }],
  },
  // Shadow Colossus: Cloak Field with armor: Detector, Corrosion and Lance.
  shade: {
    id: "shade",
    name: "Shadow Colossus",
    hp: 380,
    speed: 0.75,
    reward: 38,
    leak: 3,
    color: 0x5d4f8a,
    size: 0.33,
    layer: "ground",
    visual: { shape: "polygon", sides: 8, rotation: 0.4 },
    traits: [{ kind: "cloakField", radius: 1.8 }, { kind: "armor", reduction: 0.15 }],
  },
  // Jump Beetle: Jump Drive: jumps cells ahead and skips traps; Lance, Tesla and Cryo zones.
  hopper: {
    id: "hopper",
    name: "Jump Beetle",
    hp: 90,
    speed: 1.2,
    reward: 14,
    leak: 1,
    color: 0x6fbf73,
    size: 0.19,
    layer: "ground",
    visual: { shape: "star", points: 6, inner: 0.3 },
    traits: [{ kind: "blink", every: 4, jump: 2 }],
  },
  // Warp Drone: Jump Drive in the air: Flak and Tesla.
  warpdrone: {
    id: "warpdrone",
    name: "Warp Drone",
    hp: 80,
    speed: 1.3,
    reward: 15,
    leak: 1,
    color: 0x6ad1ff,
    size: 0.19,
    layer: "air",
    visual: { shape: "glider" },
    traits: [{ kind: "blink", every: 5, jump: 3 }],
  },
  // Gap Jumper: Frequent short jumps: Lance, Tesla and Cryo zones.
  gapper: {
    id: "gapper",
    name: "Gap Jumper",
    hp: 100,
    speed: 1.0,
    reward: 15,
    leak: 1,
    color: 0xf4a261,
    size: 0.2,
    layer: "ground",
    visual: { shape: "polygon", sides: 5, rotation: 0.7 },
    traits: [{ kind: "blink", every: 3, jump: 1.5 }],
  },
  // Tunnel Mole: Tunneling: faster underground and only reachable by traps and area damage; Quake, Mine and Tar Pit.
  mole: {
    id: "mole",
    name: "Tunnel Mole",
    hp: 180,
    speed: 0.95,
    reward: 20,
    leak: 2,
    color: 0x9c7a54,
    size: 0.25,
    layer: "ground",
    visual: { shape: "worm", segments: 4 },
    traits: [{ kind: "tunnel", every: 5, length: 2, speed: 2 }],
  },
  // Convoy Hauler: Link with Tank: Nova, Mortar, Corrosion and Executioner.
  hauler: {
    id: "hauler",
    name: "Convoy Hauler",
    hp: 280,
    speed: 0.8,
    reward: 28,
    leak: 2,
    color: 0xc0c7a0,
    size: 0.3,
    layer: "ground",
    visual: { shape: "polygon", sides: 6, rotation: 0.2 },
    traits: [{ kind: "link", radius: 1.5 }, { kind: "armor", reduction: 0.2 }],
  },
  // Phase Wing: Phase Shift: alternates between air and ground; Tesla and Snare Net.
  phasewing: {
    id: "phasewing",
    name: "Phase Wing",
    hp: 110,
    speed: 1.3,
    reward: 17,
    leak: 1,
    color: 0xc792ea,
    size: 0.2,
    layer: "air",
    visual: { shape: "star", points: 4, inner: 0.6 },
    traits: [{ kind: "phase", period: 3.5, air: 1.5 }],
  },
  // Dazzler: Dazzle: nearby towers lose range; Lance, Mortar and Jammer.
  flare: {
    id: "flare",
    name: "Dazzler",
    hp: 160,
    speed: 0.95,
    reward: 20,
    leak: 2,
    color: 0xfff27a,
    size: 0.24,
    layer: "ground",
    visual: { shape: "star", points: 12, inner: 0.5 },
    traits: [{ kind: "blind", radius: 2.5, range: 0.3 }],
  },
  // Disruption Cloud: Interference: nearby towers fire slower; Flak, Tesla and Aura.
  staticloud: {
    id: "staticloud",
    name: "Disruption Cloud",
    hp: 140,
    speed: 0.9,
    reward: 22,
    leak: 2,
    color: 0x90a4b8,
    size: 0.26,
    layer: "air",
    visual: { shape: "orb", moons: 6 },
    traits: [{ kind: "jam", radius: 2, slow: 0.4 }],
  },
  // Pioneer: Defuser: nearby traps do not trigger; Pulse, Lance and Jammer.
  sapper: {
    id: "sapper",
    name: "Pioneer",
    hp: 140,
    speed: 1.05,
    reward: 18,
    leak: 1,
    color: 0xd4a373,
    size: 0.22,
    layer: "ground",
    visual: { shape: "polygon", sides: 4, rotation: 0.9 },
    traits: [{ kind: "defuse", radius: 1.5 }, { kind: "armor", reduction: 0.1 }],
  },
  // Null-Field Carrier: Null Field: nearby support is ineffective; Jammer, Lance and Mortar.
  nullbearer: {
    id: "nullbearer",
    name: "Null-Field Carrier",
    hp: 210,
    speed: 0.9,
    reward: 26,
    leak: 2,
    color: 0x7a8899,
    size: 0.28,
    layer: "ground",
    visual: { shape: "polygon", sides: 9 },
    traits: [{ kind: "suppress", radius: 2.5 }],
  },
  // Thornback: Retaliation: nearby towers reload slower after a hit; Lance, Mortar, Ember and traps.
  thornback: {
    id: "thornback",
    name: "Thornback",
    hp: 240,
    speed: 0.9,
    reward: 26,
    leak: 2,
    color: 0x8bb174,
    size: 0.29,
    layer: "ground",
    visual: { shape: "star", points: 7, inner: 0.45 },
    traits: [{ kind: "retaliate", radius: 1.8, cycles: 0.5 }],
  },
} satisfies Record<string, EnemyDefinition>;
export const ENEMIES: Readonly<Record<EnemyId, Readonly<EnemyDefinition>>> =
  ENEMY_CONTENT;
