import type { EnemyDefinition, EnemyId } from "../core/types";
export const ENEMY_CONTENT = {
  drone: {
    id: "drone",
    name: "Drohne",
    hp: 55,
    speed: 1.45,
    reward: 9,
    leak: 1,
    color: 0xf0cf87,
    size: 0.19,
    layer: "ground",
    visual: { shape: "polygon", sides: 4 },
  },
  runner: {
    id: "runner",
    name: "Sprinter",
    hp: 40,
    speed: 2.35,
    reward: 10,
    leak: 1,
    color: 0xff947d,
    size: 0.16,
    layer: "ground",
    visual: { shape: "polygon", sides: 3 },
  },
  tank: {
    id: "tank",
    name: "Panzer",
    hp: 210,
    speed: 0.95,
    reward: 20,
    leak: 2,
    color: 0xea9bda,
    size: 0.27,
    layer: "ground",
    visual: { shape: "polygon", sides: 4, rotation: Math.PI / 4 },
  },
  boss: {
    id: "boss",
    name: "Titan",
    hp: 1600,
    speed: 0.65,
    reward: 100,
    leak: 10,
    color: 0xff647c,
    size: 0.38,
    layer: "ground",
    visual: { shape: "polygon", sides: 8 },
  },
  glider: {
    id: "glider",
    name: "Gleiter",
    hp: 45,
    speed: 1.9,
    reward: 11,
    leak: 1,
    color: 0xbfe9ff,
    size: 0.18,
    layer: "air",
    visual: { shape: "glider" },
  },
  // --- Trait enemies, introduced from Sektor II on ---
  // Eisläufer: schneller Läufer, immun gegen Verlangsamung, Glut statt Kryo.
  skater: {
    id: "skater",
    name: "Eisläufer",
    hp: 50,
    speed: 1.8,
    reward: 11,
    leak: 1,
    color: 0x9fe6ff,
    size: 0.17,
    layer: "ground",
    visual: { shape: "polygon", sides: 3, rotation: Math.PI },
    traits: [{ kind: "slowImmune" }, { kind: "swift", speed: 0.35, hp: 0.2 }],
  },
  // Splitter: zerfällt beim Tod in Drohnen, Lanzen auf den Geraden.
  splitter: {
    id: "splitter",
    name: "Splitter",
    hp: 120,
    speed: 1.1,
    reward: 12,
    leak: 2,
    color: 0xc6b4ff,
    size: 0.24,
    layer: "ground",
    visual: { shape: "polygon", sides: 6 },
    traits: [{ kind: "splitOnDeath", type: "drone", count: 3 }],
  },
  // Skarabäus: gepanzerter Läufer, Wucht und Fallen statt Streufeuer.
  scarab: {
    id: "scarab",
    name: "Skarabäus",
    hp: 80,
    speed: 1.5,
    reward: 14,
    leak: 1,
    color: 0xd9a441,
    size: 0.2,
    layer: "ground",
    visual: { shape: "polygon", sides: 6, rotation: Math.PI / 6 },
    traits: [{ kind: "armor", reduction: 0.3 }, { kind: "swift", speed: 0.3, hp: 0.15 }],
  },
  // Gräber: taucht ab, nur Fallen und Flächenschaden treffen ihn unter der Erde.
  burrower: {
    id: "burrower",
    name: "Gräber",
    hp: 140,
    speed: 1.05,
    reward: 16,
    leak: 2,
    color: 0xb98a52,
    size: 0.24,
    layer: "ground",
    visual: { shape: "polygon", sides: 5, rotation: Math.PI / 2 },
    traits: [{ kind: "burrow", every: 3, length: 1.2 }],
  },
  // Böenläufer: rast in kurzen Schüben, wer ihn trifft, muss das Tempo vorhalten.
  gale: {
    id: "gale",
    name: "Böenläufer",
    hp: 110,
    speed: 1.2,
    reward: 14,
    leak: 1,
    color: 0x9fd8ff,
    size: 0.21,
    layer: "ground",
    visual: { shape: "polygon", sides: 3, rotation: Math.PI },
    traits: [{ kind: "surge", every: 4, length: 1, factor: 2.2 }],
  },
  // Sturmvogel: schneller Flieger mit Schild, Flak und Impuls müssen ihn schnell brechen.
  stormbird: {
    id: "stormbird",
    name: "Sturmvogel",
    hp: 70,
    speed: 1.6,
    reward: 15,
    leak: 1,
    color: 0xc8e8ff,
    size: 0.2,
    layer: "air",
    visual: { shape: "glider" },
    traits: [{ kind: "shield", capacity: 0.5, delay: 2.5 }, { kind: "swift", speed: 0.2, hp: 0.1 }],
  },
  // Schwarmameise: schwach allein, im Rudel kaum zu knacken; Flächenschaden lohnt.
  ant: {
    id: "ant",
    name: "Schwarmameise",
    hp: 45,
    speed: 1.35,
    reward: 7,
    leak: 1,
    color: 0xb6ff6a,
    size: 0.15,
    layer: "ground",
    visual: { shape: "polygon", sides: 6 },
    traits: [{ kind: "swarm", radius: 1.0, per: 0.1, max: 0.5 }],
  },
  // Urwaldkoloss: gepanzert und regenerierend, braucht Wucht statt Dauerfeuer.
  colossus: {
    id: "colossus",
    name: "Urwaldkoloss",
    hp: 420,
    speed: 0.7,
    reward: 40,
    leak: 3,
    color: 0x4f9a3a,
    size: 0.34,
    layer: "ground",
    visual: { shape: "polygon", sides: 8, rotation: Math.PI / 8 },
    traits: [{ kind: "armor", reduction: 0.25 }, { kind: "regen", percent: 0.015 }],
  },
  // Panzerkrebs: wird mit jeder Wunde zäher, Burst und Zerfall schlagen Dauerfeuer.
  crab: {
    id: "crab",
    name: "Panzerkrebs",
    hp: 260,
    speed: 0.8,
    reward: 24,
    leak: 2,
    color: 0xff7a5c,
    size: 0.28,
    layer: "ground",
    visual: { shape: "polygon", sides: 8 },
    traits: [{ kind: "harden", max: 0.6 }],
  },
  // Glutläufer: wird schneller, je mehr HP fehlen; Frost, Stase, Teer und Henker bremsen oder beenden ihn.
  ember: {
    id: "ember",
    name: "Glutläufer",
    hp: 100,
    speed: 1.2,
    reward: 15,
    leak: 1,
    color: 0xff6a2a,
    size: 0.2,
    layer: "ground",
    visual: { shape: "polygon", sides: 5, rotation: -Math.PI / 2 },
    traits: [{ kind: "rage", max: 1.0 }],
  },
  // Aschenschwinge: gepanzerter Flieger, immun gegen Verlangsamung; Flak und Tesla holen ihn herunter.
  ashwing: {
    id: "ashwing",
    name: "Aschenschwinge",
    hp: 130,
    speed: 1.0,
    reward: 18,
    leak: 2,
    color: 0xb8b2ac,
    size: 0.24,
    layer: "air",
    visual: { shape: "polygon", sides: 4, rotation: Math.PI / 4 },
    traits: [{ kind: "armor", reduction: 0.25 }, { kind: "slowImmune" }],
  },
  // Kristallwächter: härtet sich im Takt gegen Treffer, Brand wirkt voll; Frost und Teer halten ihn länger in Reichweite.
  golem: {
    id: "golem",
    name: "Kristallwächter",
    hp: 320,
    speed: 0.8,
    reward: 28,
    leak: 2,
    color: 0x5ef2e0,
    size: 0.29,
    layer: "ground",
    visual: { shape: "polygon", sides: 6, rotation: Math.PI / 6 },
    traits: [{ kind: "facet", every: 4, length: 2, reduction: 0.7 }],
  },
  // Splitterfalter: schneller Flieger, zerfällt in zwei Gleiter; Flak und Tesla räumen die Schwärme.
  moth: {
    id: "moth",
    name: "Splitterfalter",
    hp: 70,
    speed: 1.45,
    reward: 12,
    leak: 1,
    color: 0xc79cf5,
    size: 0.2,
    layer: "air",
    visual: { shape: "polygon", sides: 3, rotation: 0 },
    traits: [{ kind: "splitOnDeath", type: "glider", count: 2 }],
  },
  // Luftschiff: schwer gepanzerter Flieger, wirft beim Absturz Gleiter ab; aufgerüstete Flak und Tesla holen es herunter.
  airship: {
    id: "airship",
    name: "Luftschiff",
    hp: 300,
    speed: 0.75,
    reward: 30,
    leak: 2,
    color: 0x8fa3b8,
    size: 0.32,
    layer: "air",
    visual: { shape: "polygon", sides: 6, rotation: 0 },
    traits: [{ kind: "armor", reduction: 0.2 }, { kind: "splitOnDeath", type: "glider", count: 3 }],
  },
  // Qualle: schwebender Heiler, Flak holt sie herunter.
  jelly: {
    id: "jelly",
    name: "Qualle",
    hp: 90,
    speed: 1.2,
    reward: 15,
    leak: 1,
    color: 0x7af0e0,
    size: 0.22,
    layer: "air",
    visual: { shape: "polygon", sides: 7, tentacles: 5 },
    traits: [{ kind: "healer", radius: 1.4, percent: 0.03 }],
  },
  // Schleimer: regeneriert, Burst-Schaden schlägt Dauerfeuer.
  slime: {
    id: "slime",
    name: "Schleimer",
    hp: 150,
    speed: 1.0,
    reward: 15,
    leak: 2,
    color: 0xa6d65a,
    size: 0.25,
    layer: "ground",
    visual: { shape: "polygon", sides: 7 },
    traits: [{ kind: "regen", percent: 0.02 }],
  },
  // Sanitäter: heilt Umstehende, zuerst töten.
  mender: {
    id: "mender",
    name: "Sanitäter",
    hp: 90,
    speed: 1.15,
    reward: 16,
    leak: 1,
    color: 0x7dffb0,
    size: 0.21,
    layer: "ground",
    visual: { shape: "polygon", sides: 5 },
    traits: [{ kind: "healer", radius: 1.5, percent: 0.04 }],
  },
  // Schildträger: Schild regeneriert nach kurzer Pause.
  aegis: {
    id: "aegis",
    name: "Schildträger",
    hp: 85,
    speed: 1.15,
    reward: 16,
    leak: 2,
    color: 0x8fa8ff,
    size: 0.24,
    layer: "ground",
    visual: { shape: "polygon", sides: 6, rotation: Math.PI / 6 },
    traits: [{ kind: "shield", capacity: 0.6, delay: 3 }],
  },
  // Phantom: getarnt, nur mit Detektor angreifbar.
  phantom: {
    id: "phantom",
    name: "Phantom",
    hp: 65,
    speed: 1.6,
    reward: 14,
    leak: 1,
    color: 0xd0d6ff,
    size: 0.18,
    layer: "ground",
    visual: { shape: "polygon", sides: 3 },
    traits: [{ kind: "stealth" }],
  },
  // Bollwerk: schwere Rüstung, braucht Wucht statt Streufeuer.
  bulwark: {
    id: "bulwark",
    name: "Bollwerk",
    hp: 200,
    speed: 0.85,
    reward: 26,
    leak: 2,
    color: 0xb0b8c0,
    size: 0.3,
    layer: "ground",
    visual: { shape: "polygon", sides: 4 },
    traits: [{ kind: "armor", reduction: 0.35 }],
  },
  // Kommandant: stärkt Gegner in der Nähe.
  warlord: {
    id: "warlord",
    name: "Kommandant",
    hp: 240,
    speed: 0.8,
    reward: 36,
    leak: 3,
    color: 0xe0a84f,
    size: 0.3,
    layer: "ground",
    visual: { shape: "polygon", sides: 5, rotation: Math.PI },
    traits: [{ kind: "leader", radius: 1.6, speed: 0.2, resist: 0.15 }],
  },
  // Phasenläufer: weicht periodisch Treffern aus.
  blinker: {
    id: "blinker",
    name: "Phasenläufer",
    hp: 70,
    speed: 1.7,
    reward: 13,
    leak: 1,
    color: 0xff7de9,
    size: 0.17,
    layer: "ground",
    visual: { shape: "polygon", sides: 4, rotation: Math.PI / 4 },
    traits: [{ kind: "evade", every: 3 }],
  },
  // Berserker: nicht aufzuhalten, sprintet bei halber Gesundheit.
  berserker: {
    id: "berserker",
    name: "Berserker",
    hp: 240,
    speed: 1.0,
    reward: 25,
    leak: 2,
    color: 0xff5a3d,
    size: 0.28,
    layer: "ground",
    visual: { shape: "polygon", sides: 6 },
    traits: [{ kind: "unstoppable" }, { kind: "sprint", threshold: 0.5, factor: 1.7, duration: 2.5 }],
  },
  // Sprungspinne: springt periodisch in die Luft; Impuls, Tesla und Lanze treffen beide Ebenen.
  leaper: {
    id: "leaper",
    name: "Sprungspinne",
    hp: 95,
    speed: 1.35,
    reward: 16,
    leak: 1,
    color: 0x9be15d,
    size: 0.2,
    layer: "ground",
    visual: { shape: "star", points: 8, inner: 0.45 },
    traits: [{ kind: "leap", every: 3, length: 1 }],
  },
  // Tauchflosser: Flieger, der zum Boden abtaucht; Impuls, Tesla und Schrapnell treffen ihn immer.
  skimmer: {
    id: "skimmer",
    name: "Tauchflosser",
    hp: 85,
    speed: 1.5,
    reward: 16,
    leak: 1,
    color: 0x4fd1ff,
    size: 0.21,
    layer: "air",
    visual: { shape: "glider" },
    traits: [
      { kind: "leap", every: 4, length: 1.5 },
      { kind: "swift", speed: 0.2, hp: 0.1 },
    ],
  },
  // Dämpfer: macht sich und Nachbarn immun gegen Kontrolle; Lanze, Fokus oder Störsender.
  warden: {
    id: "warden",
    name: "Dämpfer",
    hp: 170,
    speed: 0.95,
    reward: 24,
    leak: 2,
    color: 0x8a7dff,
    size: 0.26,
    layer: "ground",
    visual: { shape: "orb", moons: 3 },
    traits: [{ kind: "dampen", radius: 1.6 }],
  },
  // Brutmutter: gepanzert, legt unterwegs Schwarmameisen; Fokus, Lanze, Zerfall, Störsender stoppt die Brut.
  broodmother: {
    id: "broodmother",
    name: "Brutmutter",
    hp: 400,
    speed: 0.72,
    reward: 36,
    leak: 3,
    color: 0xc2a14a,
    size: 0.34,
    layer: "ground",
    visual: { shape: "polygon", sides: 7, tentacles: 6 },
    traits: [
      { kind: "brood", type: "ant", every: 2.5, max: 4 },
      { kind: "armor", reduction: 0.15 },
    ],
  },
  // Funkenwurm: legt beim Tod Türme in der Nähe lahm; Lanze, Mörser oder Fallen fern der Türme.
  sparkworm: {
    id: "sparkworm",
    name: "Funkenwurm",
    hp: 210,
    speed: 1.0,
    reward: 22,
    leak: 2,
    color: 0xffe14d,
    size: 0.27,
    layer: "ground",
    visual: { shape: "worm", segments: 5 },
    traits: [{ kind: "overload", radius: 1.8, cycles: 2 }],
  },
  // Häutling: erst gepanzert, unter halber Gesundheit schnell; Zerfall und Fokus, danach Kryo.
  molter: {
    id: "molter",
    name: "Häutling",
    hp: 240,
    speed: 0.85,
    reward: 24,
    leak: 2,
    color: 0xd96b8a,
    size: 0.28,
    layer: "ground",
    visual: { shape: "polygon", sides: 6, rotation: 0.5 },
    traits: [{ kind: "molt", threshold: 0.5, armor: 0.5, speed: 1.8 }],
  },
  // Irrlicht: getarnter Flieger, der Treffern ausweicht; Detektor mit Flak oder Tesla, Glut.
  wisp: {
    id: "wisp",
    name: "Irrlicht",
    hp: 60,
    speed: 1.55,
    reward: 15,
    leak: 1,
    color: 0xb8fff4,
    size: 0.18,
    layer: "air",
    visual: { shape: "orb", moons: 0 },
    traits: [{ kind: "stealth" }, { kind: "evade", every: 4 }],
  },
  // Hydra: regeneriert und teilt sich in zwei Hydraköpfe; Störsender, Nova, Beben.
  hydra: {
    id: "hydra",
    name: "Hydra",
    hp: 280,
    speed: 0.85,
    reward: 28,
    leak: 2,
    color: 0x2fbf8f,
    size: 0.3,
    layer: "ground",
    visual: { shape: "polygon", sides: 5, tentacles: 3 },
    traits: [
      { kind: "regen", percent: 0.012 },
      { kind: "splitOnDeath", type: "hydraling", count: 2 },
    ],
  },
  // Hydrakopf: Teilstück der Hydra, wird verwundet schneller; Nova, Schrapnell, Henker.
  hydraling: {
    id: "hydraling",
    name: "Hydrakopf",
    hp: 70,
    speed: 1.35,
    reward: 8,
    leak: 1,
    color: 0x5ff2b4,
    size: 0.18,
    layer: "ground",
    visual: { shape: "star", points: 5, inner: 0.55 },
    traits: [{ kind: "rage", max: 0.8 }],
  },
  // Gewitterzelle: Flieger mit Schild, legt beim Tod Türme lahm; Flak, Tesla, Störsender.
  stormcell: {
    id: "stormcell",
    name: "Gewitterzelle",
    hp: 160,
    speed: 0.85,
    reward: 26,
    leak: 2,
    color: 0x6f8bff,
    size: 0.27,
    layer: "air",
    visual: { shape: "orb", moons: 4 },
    traits: [
      { kind: "overload", radius: 1.5, cycles: 1 },
      { kind: "shield", capacity: 0.3, delay: 3 },
    ],
  },
  // Zahnrad: wird mit jedem Feld schneller; Kryo, Gravitron (Sog nimmt den Schwung) und Tesla.
  cog: {
    id: "cog",
    name: "Zahnrad",
    hp: 90,
    speed: 1.25,
    reward: 13,
    leak: 1,
    color: 0xd9a441,
    size: 0.2,
    layer: "ground",
    visual: { shape: "star", points: 8, inner: 0.7 },
    traits: [{ kind: "momentum", per: 0.03, max: 0.9 }],
  },
  // Kolbenpanzer: gepanzert und mit jeder Runde härter; Zerfall, Fokus und Lanze, am besten in der ersten Runde.
  piston: {
    id: "piston",
    name: "Kolbenpanzer",
    hp: 300,
    speed: 0.85,
    reward: 30,
    leak: 2,
    color: 0xb8742e,
    size: 0.3,
    layer: "ground",
    visual: { shape: "polygon", sides: 4, rotation: Math.PI / 4 },
    traits: [{ kind: "armor", reduction: 0.2 }, { kind: "lap", per: 0.15, max: 0.6 }],
  },
  // Gischtflügler: schneller Flieger, der mit jeder Runde härter wird; Flak und Tesla.
  tidewing: {
    id: "tidewing",
    name: "Gischtflügler",
    hp: 85,
    speed: 1.5,
    reward: 14,
    leak: 1,
    color: 0xbcd6f0,
    size: 0.2,
    layer: "air",
    visual: { shape: "glider" },
    traits: [{ kind: "lap", per: 0.12, max: 0.48 }],
  },
  // Nautilus: geschildert und mit Schwung; Störsender, Gravitron und Zerfall.
  nautilus: {
    id: "nautilus",
    name: "Nautilus",
    hp: 360,
    speed: 0.75,
    reward: 34,
    leak: 2,
    color: 0x7fa8d8,
    size: 0.31,
    layer: "ground",
    visual: { shape: "orb", moons: 0 },
    traits: [{ kind: "shield", capacity: 0.4, delay: 3 }, { kind: "momentum", per: 0.02, max: 0.8 }],
  },
  // --- Neue Eigenschaften: noch in keiner Mission platziert ---
  // Prismenläufer: Brechung: Sofort-Treffer halbiert; Impuls, Nova und Mörser.
  prism: {
    id: "prism",
    name: "Prismenläufer",
    hp: 140,
    speed: 1.1,
    reward: 16,
    leak: 1,
    color: 0x7fd3e8,
    size: 0.22,
    layer: "ground",
    visual: { shape: "star", points: 6, inner: 0.6 },
    traits: [{ kind: "refract", factor: 0.5 }],
  },
  // Spiegelflügler: Brechung in der Luft: Tesla halbiert; Flak und Impuls.
  mirrorwing: {
    id: "mirrorwing",
    name: "Spiegelflügler",
    hp: 110,
    speed: 1.35,
    reward: 17,
    leak: 1,
    color: 0xb9c7ff,
    size: 0.21,
    layer: "air",
    visual: { shape: "glider" },
    traits: [{ kind: "refract", factor: 0.5 }],
  },
  // Druckbunker: Druckfest: Flächenschaden stark gemindert; Impuls, Fokus, Lanze und Korrosion.
  bunker: {
    id: "bunker",
    name: "Druckbunker",
    hp: 340,
    speed: 0.75,
    reward: 30,
    leak: 2,
    color: 0x8a8f7a,
    size: 0.31,
    layer: "ground",
    visual: { shape: "polygon", sides: 6, rotation: Math.PI / 2 },
    traits: [{ kind: "blastproof", reduction: 0.6 }, { kind: "armor", reduction: 0.1 }],
  },
  // Geröllschwarm: Druckfest und im Schwarm zäh: Tesla, Schrapnell und Krähenfüße.
  pebble: {
    id: "pebble",
    name: "Geröllschwarm",
    hp: 38,
    speed: 1.4,
    reward: 8,
    leak: 1,
    color: 0xc9a36b,
    size: 0.15,
    layer: "ground",
    visual: { shape: "polygon", sides: 5, rotation: 0.3 },
    traits: [{ kind: "blastproof", reduction: 0.5 }, { kind: "swarm", radius: 1, per: 0.08, max: 0.4 }],
  },
  // Isolator: Isoliert: Tesla-Ketten brechen an ihm ab; Nova, Impuls und Mörser.
  insulator: {
    id: "insulator",
    name: "Isolator",
    hp: 170,
    speed: 1.0,
    reward: 18,
    leak: 2,
    color: 0xd8c24a,
    size: 0.25,
    layer: "ground",
    visual: { shape: "orb", moons: 1 },
    traits: [{ kind: "insulated" }],
  },
  // Salamander: Hitzeschild: immun gegen Brand und Blutung; Impuls, Zerfall und Nova.
  salamander: {
    id: "salamander",
    name: "Salamander",
    hp: 150,
    speed: 1.15,
    reward: 18,
    leak: 1,
    color: 0xff7a3d,
    size: 0.22,
    layer: "ground",
    visual: { shape: "worm", segments: 3 },
    traits: [{ kind: "heatshield" }],
  },
  // Magmafalter: Hitzeschild in der Luft: Flak und Tesla statt Glut.
  cinderwing: {
    id: "cinderwing",
    name: "Magmafalter",
    hp: 100,
    speed: 1.4,
    reward: 16,
    leak: 1,
    color: 0xff9f5a,
    size: 0.2,
    layer: "air",
    visual: { shape: "glider" },
    traits: [{ kind: "heatshield" }],
  },
  // Monolith: Spiegelpanzer: jeder Treffer höchstens 6 % der HP; Tesla, Impuls, Glut und Henker.
  monolith: {
    id: "monolith",
    name: "Monolith",
    hp: 520,
    speed: 0.6,
    reward: 42,
    leak: 3,
    color: 0x9aa7b8,
    size: 0.36,
    layer: "ground",
    visual: { shape: "polygon", sides: 4, rotation: Math.PI / 8 },
    traits: [{ kind: "mirror", cap: 0.06 }],
  },
  // Zwillingsläufer: Verbund: teilt Schaden mit Artgenossen im Radius; Nova, Mörser und Henker.
  twin: {
    id: "twin",
    name: "Zwillingsläufer",
    hp: 120,
    speed: 1.1,
    reward: 14,
    leak: 1,
    color: 0xa3e07a,
    size: 0.21,
    layer: "ground",
    visual: { shape: "orb", moons: 2 },
    traits: [{ kind: "link", radius: 1.6 }],
  },
  // Kettenqualle: Verbund in der Luft: Tesla und Flak.
  chainling: {
    id: "chainling",
    name: "Kettenqualle",
    hp: 75,
    speed: 1.35,
    reward: 13,
    leak: 1,
    color: 0x7ae0c8,
    size: 0.19,
    layer: "air",
    visual: { shape: "polygon", sides: 7, tentacles: 3 },
    traits: [{ kind: "link", radius: 1.4 }],
  },
  // Lockvogel: Köder: Türme im Radius müssen ihn anvisieren; Korrosion, Zerfall und Henker.
  decoy: {
    id: "decoy",
    name: "Lockvogel",
    hp: 260,
    speed: 0.85,
    reward: 28,
    leak: 2,
    color: 0xe0607a,
    size: 0.29,
    layer: "ground",
    visual: { shape: "star", points: 5, inner: 0.5 },
    traits: [{ kind: "taunt", radius: 2.5 }, { kind: "armor", reduction: 0.3 }],
  },
  // Leuchtboje: Köder mit Schild in der Luft: Flak, Tesla und Störsender.
  buoy: {
    id: "buoy",
    name: "Leuchtboje",
    hp: 160,
    speed: 0.9,
    reward: 24,
    leak: 2,
    color: 0xffd166,
    size: 0.26,
    layer: "air",
    visual: { shape: "orb", moons: 5 },
    traits: [{ kind: "taunt", radius: 2 }, { kind: "shield", capacity: 0.4, delay: 3 }],
  },
  // Märtyrer: Opfergabe: heilt beim Tod seine Nachbarn; Nova, Mörser und Störsender.
  martyr: {
    id: "martyr",
    name: "Märtyrer",
    hp: 110,
    speed: 1.1,
    reward: 14,
    leak: 1,
    color: 0xf2e6c9,
    size: 0.21,
    layer: "ground",
    visual: { shape: "polygon", sides: 3, rotation: Math.PI / 2 },
    traits: [{ kind: "martyr", radius: 1.8, heal: 0.25 }],
  },
  // Seelenfunke: Opfergabe in der Luft: Flak und Tesla.
  soulspark: {
    id: "soulspark",
    name: "Seelenfunke",
    hp: 60,
    speed: 1.55,
    reward: 12,
    leak: 1,
    color: 0xe8d4ff,
    size: 0.17,
    layer: "air",
    visual: { shape: "star", points: 4, inner: 0.4 },
    traits: [{ kind: "martyr", radius: 1.5, heal: 0.12 }],
  },
  // Rudelwolf: Rudel: wird mit jedem Nachbarn schneller; Kryo, Nova und Gravitron.
  wolf: {
    id: "wolf",
    name: "Rudelwolf",
    hp: 75,
    speed: 1.3,
    reward: 11,
    leak: 1,
    color: 0xb8c4d0,
    size: 0.19,
    layer: "ground",
    visual: { shape: "polygon", sides: 5, rotation: Math.PI },
    traits: [{ kind: "pack", radius: 1.5, perAlly: 0.08, max: 0.4 }],
  },
  // Sturmfalke: Rudel in der Luft: Tesla und Flak.
  raptor: {
    id: "raptor",
    name: "Sturmfalke",
    hp: 65,
    speed: 1.6,
    reward: 12,
    leak: 1,
    color: 0xd9a066,
    size: 0.18,
    layer: "air",
    visual: { shape: "glider" },
    traits: [{ kind: "pack", radius: 1.5, perAlly: 0.1, max: 0.5 }],
  },
  // Kolonnenläufer: Rudel im Windschatten: Kryo, Nova und Gravitron.
  drafter: {
    id: "drafter",
    name: "Kolonnenläufer",
    hp: 70,
    speed: 1.35,
    reward: 11,
    leak: 1,
    color: 0xa8e6ef,
    size: 0.18,
    layer: "ground",
    visual: { shape: "polygon", sides: 3, rotation: -Math.PI / 2 },
    traits: [{ kind: "pack", radius: 1.5, perAlly: 0.08, max: 0.4 }],
  },
  // Schleierweber: Tarnfeld: tarnt Nachbarn bis ein Detektor sie erfasst; Detektor, Lanze und Mörser.
  veiler: {
    id: "veiler",
    name: "Schleierweber",
    hp: 130,
    speed: 1.0,
    reward: 20,
    leak: 2,
    color: 0x8e7cc3,
    size: 0.23,
    layer: "ground",
    visual: { shape: "polygon", sides: 7, rotation: 0.2, tentacles: 2 },
    traits: [{ kind: "cloakField", radius: 1.6 }],
  },
  // Schattenkoloss: Tarnfeld mit Panzer: Detektor, Korrosion und Lanze.
  shade: {
    id: "shade",
    name: "Schattenkoloss",
    hp: 380,
    speed: 0.75,
    reward: 38,
    leak: 3,
    color: 0x5d4f8a,
    size: 0.33,
    layer: "ground",
    visual: { shape: "polygon", sides: 8, rotation: 0.4 },
    traits: [{ kind: "cloakField", radius: 1.8 }, { kind: "armor", reduction: 0.15 }],
  },
  // Sprungkäfer: Sprungantrieb: springt Felder voraus und überspringt Fallen; Lanze, Tesla und Kryo-Zonen.
  hopper: {
    id: "hopper",
    name: "Sprungkäfer",
    hp: 90,
    speed: 1.2,
    reward: 14,
    leak: 1,
    color: 0x6fbf73,
    size: 0.19,
    layer: "ground",
    visual: { shape: "star", points: 6, inner: 0.3 },
    traits: [{ kind: "blink", every: 4, jump: 2 }],
  },
  // Warpdrohne: Sprungantrieb in der Luft: Flak und Tesla.
  warpdrone: {
    id: "warpdrone",
    name: "Warpdrohne",
    hp: 80,
    speed: 1.3,
    reward: 15,
    leak: 1,
    color: 0x6ad1ff,
    size: 0.19,
    layer: "air",
    visual: { shape: "glider" },
    traits: [{ kind: "blink", every: 5, jump: 3 }],
  },
  // Lückenspringer: Häufige kurze Sprünge: Lanze, Tesla und Kryo-Zonen.
  gapper: {
    id: "gapper",
    name: "Lückenspringer",
    hp: 100,
    speed: 1.0,
    reward: 15,
    leak: 1,
    color: 0xf4a261,
    size: 0.2,
    layer: "ground",
    visual: { shape: "polygon", sides: 5, rotation: 0.7 },
    traits: [{ kind: "blink", every: 3, jump: 1.5 }],
  },
  // Tunnelmaulwurf: Tunnelgang: unter der Erde schneller und nur für Fallen und Fläche greifbar; Beben, Mine und Teergrube.
  mole: {
    id: "mole",
    name: "Tunnelmaulwurf",
    hp: 180,
    speed: 0.95,
    reward: 20,
    leak: 2,
    color: 0x9c7a54,
    size: 0.25,
    layer: "ground",
    visual: { shape: "worm", segments: 4 },
    traits: [{ kind: "tunnel", every: 5, length: 2, speed: 2 }],
  },
  // Konvoischlepper: Verbund mit Panzer: Nova, Mörser, Korrosion und Henker.
  hauler: {
    id: "hauler",
    name: "Konvoischlepper",
    hp: 280,
    speed: 0.8,
    reward: 28,
    leak: 2,
    color: 0xc0c7a0,
    size: 0.3,
    layer: "ground",
    visual: { shape: "polygon", sides: 6, rotation: 0.2 },
    traits: [{ kind: "link", radius: 1.5 }, { kind: "armor", reduction: 0.2 }],
  },
  // Phasenflügler: Phasenwechsel: wechselt zwischen Luft und Boden; Tesla und Fangnetz.
  phasewing: {
    id: "phasewing",
    name: "Phasenflügler",
    hp: 110,
    speed: 1.3,
    reward: 17,
    leak: 1,
    color: 0xc792ea,
    size: 0.2,
    layer: "air",
    visual: { shape: "star", points: 4, inner: 0.6 },
    traits: [{ kind: "phase", period: 3.5, air: 1.5 }],
  },
  // Blender: Blendlicht: Türme in der Nähe verlieren Reichweite; Lanze, Mörser und Störsender.
  flare: {
    id: "flare",
    name: "Blender",
    hp: 160,
    speed: 0.95,
    reward: 20,
    leak: 2,
    color: 0xfff27a,
    size: 0.24,
    layer: "ground",
    visual: { shape: "star", points: 12, inner: 0.5 },
    traits: [{ kind: "blind", radius: 2.5, range: 0.3 }],
  },
  // Störwolke: Störfeld: Türme in der Nähe feuern langsamer; Flak, Tesla und Aura.
  staticloud: {
    id: "staticloud",
    name: "Störwolke",
    hp: 140,
    speed: 0.9,
    reward: 22,
    leak: 2,
    color: 0x90a4b8,
    size: 0.26,
    layer: "air",
    visual: { shape: "orb", moons: 6 },
    traits: [{ kind: "jam", radius: 2, slow: 0.4 }],
  },
  // Pionier: Entschärfer: Fallen in der Nähe lösen nicht aus; Impuls, Lanze und Störsender.
  sapper: {
    id: "sapper",
    name: "Pionier",
    hp: 140,
    speed: 1.05,
    reward: 18,
    leak: 1,
    color: 0xd4a373,
    size: 0.22,
    layer: "ground",
    visual: { shape: "polygon", sides: 4, rotation: 0.9 },
    traits: [{ kind: "defuse", radius: 1.5 }, { kind: "armor", reduction: 0.1 }],
  },
  // Nullfeldträger: Nullfeld: Unterstützung in der Nähe wirkungslos; Störsender, Lanze und Mörser.
  nullbearer: {
    id: "nullbearer",
    name: "Nullfeldträger",
    hp: 210,
    speed: 0.9,
    reward: 26,
    leak: 2,
    color: 0x7a8899,
    size: 0.28,
    layer: "ground",
    visual: { shape: "polygon", sides: 9 },
    traits: [{ kind: "suppress", radius: 2.5 }],
  },
  // Dornrücken: Vergeltung: Türme in der Nähe laden nach einem Treffer langsamer; Lanze, Mörser, Glut und Fallen.
  thornback: {
    id: "thornback",
    name: "Dornrücken",
    hp: 240,
    speed: 0.9,
    reward: 26,
    leak: 2,
    color: 0x8bb174,
    size: 0.29,
    layer: "ground",
    visual: { shape: "star", points: 7, inner: 0.45 },
    traits: [{ kind: "retaliate", radius: 1.8, cycles: 0.5 }],
  },
} satisfies Record<string, EnemyDefinition>;
export const ENEMIES: Readonly<Record<EnemyId, Readonly<EnemyDefinition>>> =
  ENEMY_CONTENT;
