import type { TowerDefinition, TowerId } from "../core/types";
import { attackTower, AURA_UPGRADES, DETECTOR_UPGRADES, REFINERY_UPGRADES } from "./upgrades";
export const TOWER_CONTENT = {
  pulse: attackTower({
    id: "pulse",
    name: "Impuls",
    role: "EINZELZIEL",
    description: "Schnelle, präzise Schüsse. Ideal gegen einzelne Gegner.",
    cost: 80,
    damage: 18,
    range: 2.65,
    interval: 0.55,
    color: 0x93f5b8,
    attack: { kind: "direct" },
    targets: ["ground", "air"],
    projectile: { speed: 10 },
    visual: { icon: "◉", turret: "barrel", projectile: "tracer", impact: "spark" },
  }),
  blast: attackTower({
    id: "blast",
    name: "Nova",
    role: "FLÄCHENSCHADEN",
    description: "Trifft alle Gegner im Explosionsradius. Stark gegen Gruppen.",
    cost: 130,
    damage: 40,
    range: 2.9,
    interval: 1.5,
    color: 0xffbd76,
    attack: { kind: "splash", radius: 1.25 },
    targets: ["ground"],
    projectile: { speed: 6 },
    visual: { icon: "✦", turret: "heavy", projectile: "shell", impact: "burst" },
  }),
  frost: attackTower({
    id: "frost",
    name: "Kryo",
    role: "VERLANGSAMUNG",
    description: "Verlangsamt ein Ziel um 45 %. Gibt anderen Türmen mehr Zeit.",
    cost: 100,
    damage: 9,
    range: 2.5,
    interval: 0.7,
    color: 0xa5a2ff,
    attack: { kind: "slow", factor: 0.55, duration: 1.9 },
    targets: ["ground", "air"],
    projectile: { speed: 8 },
    visual: { icon: "❖", turret: "crystal", projectile: "crystal", impact: "spark" },
  }, {
    4: {
      attack: { factor: 0.45, duration: 2.3 },
      description: "Stärkere und längere Verlangsamung, dazu mehr Schaden und Reichweite.",
    },
    5: {
      attack: { factor: 0.35, duration: 2.8 },
      description: "Tiefkühlung: Gegner laufen nur noch mit 35 % Tempo, fast drei Sekunden lang.",
    },
  }),
  aura: {
    id: "aura",
    name: "Aura",
    role: "UNTERSTÜTZUNG",
    description: "Verstärkt Angriffstürme im Radius. Wähle einen von drei Upgrade-Pfaden mit je drei Stufen; kein eigener Angriff.",
    cost: 160,
    damage: 0,
    range: 3,
    interval: 0,
    color: 0x78dfff,
    attack: { kind: "aura", base: { damage: 0, speed: 0, range: 0 } },
    targets: [],
    visual: {
      icon: "◎",
      turret: "aura",
      paths: {
        damage: { color: 0xff7a5c, motif: "blades" },
        speed: { color: 0xffd166, motif: "vortex" },
        range: { color: 0x8ef0a8, motif: "rings" },
      },
    },
    upgrades: AURA_UPGRADES,
  },
  flak: attackTower({
    id: "flak",
    name: "Flak",
    role: "LUFTABWEHR",
    description: "Schnelle Schüsse gegen Luftziele. Trifft keine Bodeneinheiten.",
    cost: 90,
    damage: 26,
    range: 3.2,
    interval: 0.45,
    color: 0xff9de2,
    attack: { kind: "direct" },
    targets: ["air"],
    projectile: { speed: 12 },
    visual: { icon: "⌖", turret: "twin", projectile: "twin", impact: "spark" },
  }),
  tesla: attackTower({
    id: "tesla",
    name: "Tesla",
    role: "KETTENBLITZ",
    description: "Der Blitz springt auf weitere Gegner in der Nähe über. Trifft Boden und Luft.",
    cost: 150,
    damage: 22,
    range: 2.6,
    interval: 1.1,
    color: 0xf7e46b,
    attack: { kind: "chain", jumps: 3, range: 1.6, falloff: 0.75 },
    targets: ["ground", "air"],
    visual: { icon: "ϟ", turret: "coil", muzzle: "bolt" },
  }, {
    4: {
      attack: { jumps: 4, range: 1.8 },
      description: "Der Blitz springt auf einen Gegner mehr und weiter, dazu mehr Schaden.",
    },
    5: {
      attack: { jumps: 5, range: 2 },
      description: "Gewitterkern: bis zu fünf Sprünge mit zwei Feldern Reichweite.",
    },
  }),
  lance: attackTower({
    id: "lance",
    name: "Lanze",
    role: "DURCHSCHLAG",
    description: "Railgun mit großer Reichweite. Der Strahl durchschlägt alle Gegner auf seiner Linie.",
    cost: 170,
    damage: 70,
    range: 4.4,
    interval: 2.4,
    color: 0xe8f1ff,
    attack: { kind: "pierce", width: 0.35, falloff: 0.85 },
    targets: ["ground", "air"],
    visual: { icon: "⟂", turret: "rail" },
  }, {
    4: {
      attack: { falloff: 0.9 },
      description: "Verdichteter Strahl: verliert pro durchschlagenem Gegner weniger Schaden.",
    },
    5: {
      attack: { width: 0.5, falloff: 1 },
      description: "Teilchenlanze: breiterer Strahl, jeder Gegner auf der Linie erhält vollen Schaden.",
    },
  }),
  inferno: attackTower({
    id: "inferno",
    name: "Glut",
    role: "BRANDSCHADEN",
    description: "Setzt Gegner in Brand. Der Brand verursacht über drei Sekunden das 2,5-Fache des Treffers.",
    cost: 120,
    damage: 10,
    range: 2.4,
    interval: 0.8,
    color: 0xff6a3d,
    attack: { kind: "burn", ratio: 2.5, duration: 3 },
    targets: ["ground", "air"],
    projectile: { speed: 7 },
    visual: { icon: "♨\uFE0E", turret: "flame", projectile: "ember", impact: "spark" },
  }, {
    4: {
      attack: { ratio: 3 },
      description: "Heißere Glut: der Brand verursacht das Dreifache des Treffers.",
    },
    5: {
      attack: { ratio: 3.5, duration: 3.5 },
      description: "Feuersturm: stärkerer und längerer Brand.",
    },
  }),
  stasis: attackTower({
    id: "stasis",
    name: "Stasis",
    role: "BETÄUBUNG",
    description: "Ein Puls hält alle Gegner im Radius kurz an. Danach sind sie 1,5 s lang immun.",
    cost: 140,
    damage: 6,
    range: 2.4,
    interval: 3,
    color: 0x5cf2d6,
    attack: { kind: "stun", radius: 0.9, duration: 0.8, recovery: 1.5 },
    targets: ["ground", "air"],
    visual: { icon: "⊛", turret: "emitter" },
  }, {
    4: {
      attack: { duration: 1, radius: 1.1 },
      description: "Längere Betäubung in einem größeren Radius.",
    },
    5: {
      attack: { duration: 1.2, radius: 1.3 },
      description: "Zeitfalle: Gegner im weiten Radius stehen 1,2 Sekunden still.",
    },
  }),
  acid: attackTower({
    id: "acid",
    name: "Korrosion",
    role: "SCHWÄCHUNG",
    description: "Säure im kleinen Radius. Getroffene Gegner erleiden 3 s lang 25 % mehr Schaden von allen Türmen.",
    cost: 110,
    damage: 12,
    range: 2.7,
    interval: 1.2,
    color: 0xb6f04a,
    attack: { kind: "corrode", radius: 0.8, amount: 0.25, duration: 3 },
    targets: ["ground", "air"],
    projectile: { speed: 6 },
    visual: { icon: "☣\uFE0E", turret: "vat", projectile: "glob", impact: "burst" },
  }, {
    4: {
      attack: { amount: 0.3 },
      description: "Konzentrierte Säure: Gegner erleiden 30 % mehr Schaden.",
    },
    5: {
      attack: { amount: 0.4, radius: 1 },
      description: "Zersetzung: 40 % mehr Schaden in einem größeren Radius.",
    },
  }),
  decay: attackTower({
    id: "decay",
    name: "Zerfall",
    role: "ANTI-BOSS",
    description: "Jeder Treffer zieht zusätzlich 4 % der maximalen Lebenspunkte ab. Stark gegen Panzer und Titanen.",
    cost: 160,
    damage: 20,
    range: 3,
    interval: 2,
    color: 0xd16bff,
    attack: { kind: "decay", percent: 0.04 },
    targets: ["ground", "air"],
    projectile: { speed: 9 },
    visual: { icon: "⬡", turret: "prism", projectile: "orb", impact: "burst" },
  }, {
    4: {
      attack: { percent: 0.05 },
      description: "Tieferer Zerfall: 5 % der maximalen Lebenspunkte pro Treffer.",
    },
    5: {
      attack: { percent: 0.06 },
      description: "Auflösung: 6 % der maximalen Lebenspunkte pro Treffer.",
    },
  }),
  refinery: {
    id: "refinery",
    name: "Raffinerie",
    role: "CREDITS",
    description: "Fördert nach jeder abgeschlossenen Welle 25 Credits. Kein eigener Angriff; lohnt sich, je früher sie steht.",
    cost: 120,
    damage: 0,
    range: 0,
    interval: 0,
    color: 0xf5c542,
    attack: { kind: "income", amount: 25 },
    targets: [],
    visual: { icon: "⚙\uFE0E", turret: "refinery" },
    upgrades: REFINERY_UPGRADES,
  },
  detector: {
    id: "detector",
    name: "Detektor",
    role: "AUFKLÄRUNG",
    description: "Deckt getarnte Gegner in seiner Reichweite auf, damit alle Türme sie anvisieren können. Kein eigener Angriff.",
    cost: 90,
    damage: 0,
    range: 3.5,
    interval: 0,
    color: 0x6fd3ff,
    attack: { kind: "detect" },
    targets: [],
    visual: { icon: "◎", turret: "radar" },
    upgrades: DETECTOR_UPGRADES,
  },
} satisfies Record<string, TowerDefinition>;
export const TOWERS: Readonly<Record<TowerId, Readonly<TowerDefinition>>> =
  TOWER_CONTENT;
