import type { TowerDefinition, TowerId } from "../core/types";
import { attackTower, AURA_UPGRADES, BEACON_UPGRADES, DETECTOR_UPGRADES, DOCK_UPGRADES, REFINERY_UPGRADES, TRACKER_UPGRADES } from "./upgrades";
export const TOWER_CONTENT = {
  pulse: attackTower({
    id: "pulse",
    name: "Impuls",
    role: "EINZELZIEL",
    description: "Schnelle, präzise Schüsse. Ideal gegen einzelne Gegner.",
    cost: 80,
    damage: 18,
    range: 2.65,
    interval: 0.55,
    color: 0x93f5b8,
    attack: { kind: "direct" },
    targets: ["ground", "air"],
    projectile: { speed: 10 },
    visual: { icon: "◉", turret: "barrel", projectile: "tracer", impact: "spark" },
  }),
  blast: attackTower({
    id: "blast",
    name: "Nova",
    role: "FLÄCHENSCHADEN",
    description: "Trifft alle Gegner im Explosionsradius. Stark gegen Gruppen.",
    cost: 130,
    damage: 40,
    range: 2.9,
    interval: 1.5,
    color: 0xffbd76,
    attack: { kind: "splash", radius: 1.25 },
    targets: ["ground"],
    projectile: { speed: 6 },
    visual: { icon: "✦", turret: "heavy", projectile: "shell", impact: "burst" },
  }),
  frost: attackTower({
    id: "frost",
    name: "Kryo",
    role: "VERLANGSAMUNG",
    description: "Verlangsamt ein Ziel um 45 %. Gibt anderen Türmen mehr Zeit.",
    cost: 100,
    damage: 9,
    range: 2.5,
    interval: 0.7,
    color: 0xa5a2ff,
    attack: { kind: "slow", factor: 0.55, duration: 1.9 },
    targets: ["ground", "air"],
    projectile: { speed: 8 },
    visual: { icon: "❖", turret: "crystal", projectile: "crystal", impact: "spark" },
  }, {
    4: {
      attack: { factor: 0.45, duration: 2.3 },
      description: "Stärkere und längere Verlangsamung, dazu mehr Schaden und Reichweite.",
    },
    5: {
      attack: { factor: 0.35, duration: 2.8 },
      description: "Tiefkühlung: Gegner laufen nur noch mit 35 % Tempo, fast drei Sekunden lang.",
    },
  }),
  aura: {
    id: "aura",
    name: "Aura",
    role: "UNTERSTÜTZUNG",
    description: "Verstärkt Angriffstürme im Radius. Wähle einen von drei Upgrade-Pfaden mit je drei Stufen; kein eigener Angriff.",
    cost: 160,
    damage: 0,
    range: 3,
    interval: 0,
    color: 0x78dfff,
    attack: { kind: "aura", base: { damage: 0, speed: 0, range: 0 } },
    targets: [],
    visual: {
      icon: "◎",
      turret: "aura",
      paths: {
        damage: { color: 0xff7a5c, motif: "blades" },
        speed: { color: 0xffd166, motif: "vortex" },
        range: { color: 0x8ef0a8, motif: "rings" },
      },
    },
    upgrades: AURA_UPGRADES,
  },
  flak: attackTower({
    id: "flak",
    name: "Flak",
    role: "LUFTABWEHR",
    description: "Schnelle Schüsse gegen Luftziele. Trifft keine Bodeneinheiten.",
    cost: 90,
    damage: 26,
    range: 3.2,
    interval: 0.45,
    color: 0xff9de2,
    attack: { kind: "direct" },
    targets: ["air"],
    projectile: { speed: 12 },
    visual: { icon: "⌖", turret: "twin", projectile: "twin", impact: "spark" },
  }),
  tesla: attackTower({
    id: "tesla",
    name: "Tesla",
    role: "KETTENBLITZ",
    description: "Der Blitz springt auf weitere Gegner in der Nähe über. Trifft Boden und Luft.",
    cost: 150,
    damage: 22,
    range: 2.6,
    interval: 1.1,
    color: 0xf7e46b,
    attack: { kind: "chain", jumps: 3, range: 1.6, falloff: 0.75 },
    targets: ["ground", "air"],
    visual: { icon: "ϟ", turret: "coil", muzzle: "bolt" },
  }, {
    4: {
      attack: { jumps: 4, range: 1.8 },
      description: "Der Blitz springt auf einen Gegner mehr und weiter, dazu mehr Schaden.",
    },
    5: {
      attack: { jumps: 5, range: 2 },
      description: "Gewitterkern: bis zu fünf Sprünge mit zwei Feldern Reichweite.",
    },
  }),
  lance: attackTower({
    id: "lance",
    name: "Lanze",
    role: "DURCHSCHLAG",
    description: "Railgun mit großer Reichweite. Der Strahl durchschlägt alle Gegner auf seiner Linie.",
    cost: 170,
    damage: 70,
    range: 4.4,
    interval: 2.4,
    color: 0xe8f1ff,
    attack: { kind: "pierce", width: 0.35, falloff: 0.85 },
    targets: ["ground", "air"],
    visual: { icon: "⟂", turret: "rail" },
  }, {
    4: {
      attack: { falloff: 0.9 },
      description: "Verdichteter Strahl: verliert pro durchschlagenem Gegner weniger Schaden.",
    },
    5: {
      attack: { width: 0.5, falloff: 1 },
      description: "Teilchenlanze: breiterer Strahl, jeder Gegner auf der Linie erhält vollen Schaden.",
    },
  }),
  inferno: attackTower({
    id: "inferno",
    name: "Glut",
    role: "BRANDSCHADEN",
    description: "Setzt Gegner in Brand. Der Brand verursacht über drei Sekunden das 2,5-Fache des Treffers.",
    cost: 120,
    damage: 10,
    range: 2.4,
    interval: 0.8,
    color: 0xff6a3d,
    attack: { kind: "burn", ratio: 2.5, duration: 3 },
    targets: ["ground", "air"],
    projectile: { speed: 7 },
    visual: { icon: "♨\uFE0E", turret: "flame", projectile: "ember", impact: "spark" },
  }, {
    4: {
      attack: { ratio: 3 },
      description: "Heißere Glut: der Brand verursacht das Dreifache des Treffers.",
    },
    5: {
      attack: { ratio: 3.5, duration: 3.5 },
      description: "Feuersturm: stärkerer und längerer Brand.",
    },
  }),
  stasis: attackTower({
    id: "stasis",
    name: "Stasis",
    role: "BETÄUBUNG",
    description: "Ein Puls hält alle Gegner im Radius kurz an. Danach sind sie 1,5 s lang immun.",
    cost: 140,
    damage: 6,
    range: 2.4,
    interval: 3,
    color: 0x5cf2d6,
    attack: { kind: "stun", radius: 0.9, duration: 0.8, recovery: 1.5 },
    targets: ["ground", "air"],
    visual: { icon: "⊛", turret: "emitter" },
  }, {
    4: {
      attack: { duration: 1, radius: 1.1 },
      description: "Längere Betäubung in einem größeren Radius.",
    },
    5: {
      attack: { duration: 1.2, radius: 1.3 },
      description: "Zeitfalle: Gegner im weiten Radius stehen 1,2 Sekunden still.",
    },
  }),
  acid: attackTower({
    id: "acid",
    name: "Korrosion",
    role: "SCHWÄCHUNG",
    description: "Säure im kleinen Radius. Getroffene Gegner erleiden 3 s lang 25 % mehr Schaden von allen Türmen.",
    cost: 110,
    damage: 12,
    range: 2.7,
    interval: 1.2,
    color: 0xb6f04a,
    attack: { kind: "corrode", radius: 0.8, amount: 0.25, duration: 3 },
    targets: ["ground", "air"],
    projectile: { speed: 6 },
    visual: { icon: "☣\uFE0E", turret: "vat", projectile: "glob", impact: "burst" },
  }, {
    4: {
      attack: { amount: 0.3 },
      description: "Konzentrierte Säure: Gegner erleiden 30 % mehr Schaden.",
    },
    5: {
      attack: { amount: 0.4, radius: 1 },
      description: "Zersetzung: 40 % mehr Schaden in einem größeren Radius.",
    },
  }),
  decay: attackTower({
    id: "decay",
    name: "Zerfall",
    role: "ANTI-BOSS",
    description: "Jeder Treffer zieht zusätzlich 4 % der maximalen Lebenspunkte ab. Stark gegen Panzer und Titanen.",
    cost: 160,
    damage: 20,
    range: 3,
    interval: 2,
    color: 0xd16bff,
    attack: { kind: "decay", percent: 0.04 },
    targets: ["ground", "air"],
    projectile: { speed: 9 },
    visual: { icon: "⬡", turret: "prism", projectile: "orb", impact: "burst" },
  }, {
    4: {
      attack: { percent: 0.05 },
      description: "Tieferer Zerfall: 5 % der maximalen Lebenspunkte pro Treffer.",
    },
    5: {
      attack: { percent: 0.06 },
      description: "Auflösung: 6 % der maximalen Lebenspunkte pro Treffer.",
    },
  }),
  focus: attackTower({
    id: "focus",
    name: "Fokus",
    role: "AUFLADUNG",
    description: "Dauerstrahl, der sein Ziel festhält. Jeder Folgetreffer auf dasselbe Ziel verursacht 20 % mehr Schaden, bis zum Dreifachen.",
    cost: 150,
    damage: 6,
    range: 2.8,
    interval: 0.3,
    color: 0xff4f8b,
    attack: { kind: "focus", ramp: 0.2, stacks: 10 },
    targets: ["ground", "air"],
    visual: { icon: "◈", turret: "lens" },
  }, {
    4: {
      attack: { ramp: 0.25 },
      description: "Schnellere Aufladung: 25 % mehr Schaden pro Folgetreffer.",
    },
    5: {
      attack: { ramp: 0.3, stacks: 12 },
      description: "Brennglas: 30 % pro Folgetreffer und zwei Stufen mehr, bis zum 4,6-Fachen.",
    },
  }),
  gravity: attackTower({
    id: "gravity",
    name: "Gravitron",
    role: "RÜCKSTOSS",
    description: "Ein Gravitationspuls zieht Bodengegner im Radius 0,6 s lang rückwärts den Pfad entlang. Danach sind sie 2,5 s lang immun.",
    cost: 170,
    damage: 8,
    range: 2.5,
    interval: 4,
    color: 0x4d7cff,
    attack: { kind: "pull", radius: 1, strength: 1.5, duration: 0.6, recovery: 2.5 },
    targets: ["ground"],
    visual: { icon: "⊚", turret: "gravity" },
  }, {
    4: {
      attack: { radius: 1.2, strength: 1.8 },
      description: "Stärkerer Zug in einem größeren Radius.",
    },
    5: {
      attack: { radius: 1.4, strength: 2.2, duration: 0.7 },
      description: "Ereignishorizont: Gegner im weiten Radius werden länger und kräftiger zurückgezogen.",
    },
  }),
  mortar: attackTower({
    id: "mortar",
    name: "Mörser",
    role: "ARTILLERIE",
    description: "Langsame Granaten mit großer Reichweite und großem Explosionsradius. Gegner näher als 1,5 Felder kann er nicht beschießen.",
    cost: 160,
    damage: 60,
    range: 5,
    interval: 3,
    color: 0xc8a46e,
    attack: { kind: "mortar", radius: 1.3, minRange: 1.5 },
    targets: ["ground"],
    projectile: { speed: 4 },
    visual: { icon: "⌓", turret: "mortar", projectile: "shell", impact: "burst" },
  }, {
    4: {
      attack: { radius: 1.5 },
      description: "Schwerere Granaten: größerer Explosionsradius, dazu mehr Schaden.",
    },
    5: {
      attack: { radius: 1.7, minRange: 1.2 },
      description: "Haubitze: riesiger Explosionsradius und ein kleinerer toter Winkel.",
    },
  }),
  quake: attackTower({
    id: "quake",
    name: "Beben",
    role: "NAHBEREICH",
    description: "Eine Schockwelle trifft alle Bodengegner in seiner Reichweite, nah am Turm voll, am Rand noch halb. Stark an Kurven.",
    cost: 140,
    damage: 30,
    range: 1.8,
    interval: 1.8,
    color: 0xa4703f,
    attack: { kind: "quake", edge: 0.5 },
    targets: ["ground"],
    visual: { icon: "≋", turret: "hammer" },
  }, {
    4: {
      attack: { edge: 0.7 },
      description: "Tiefere Welle: am Rand noch 70 % Schaden, dazu mehr Schaden und Reichweite.",
    },
    5: {
      attack: { edge: 1 },
      description: "Erdstoß: volle Wucht bis an den Rand der Reichweite.",
    },
  }),
  executioner: attackTower({
    id: "executioner",
    name: "Henker",
    role: "HINRICHTUNG",
    description: "Schwere Schüsse. Gegner unter 25 % HP erleiden beim Einschlag den vierfachen Schaden. Ideal, um angeschlagene Ziele zu erledigen.",
    cost: 150,
    damage: 40,
    range: 3,
    interval: 1.6,
    color: 0xb3122e,
    attack: { kind: "execute", threshold: 0.25, multiplier: 4 },
    targets: ["ground", "air"],
    projectile: { speed: 11 },
    visual: { icon: "⚔\uFE0E", turret: "blade", projectile: "tracer", impact: "spark" },
  }, {
    4: {
      attack: { threshold: 0.3 },
      description: "Hinrichtung schon unter 30 % HP, dazu mehr Schaden.",
    },
    5: {
      attack: { threshold: 0.35, multiplier: 5 },
      description: "Scharfrichter: fünffacher Schaden unter 35 % HP.",
    },
  }),
  shrapnel: attackTower({
    id: "shrapnel",
    name: "Schrapnell",
    role: "MEHRFACHZIEL",
    description: "Jede Salve trifft bis zu drei verschiedene Gegner gleichzeitig. Stark gegen Schwärme am Boden und in der Luft.",
    cost: 130,
    damage: 14,
    range: 2.6,
    interval: 0.9,
    color: 0x9fb4c7,
    attack: { kind: "volley", targets: 3 },
    targets: ["ground", "air"],
    projectile: { speed: 11 },
    visual: { icon: "⁂", turret: "scatter", projectile: "crystal", impact: "spark" },
  }, {
    4: {
      attack: { targets: 4 },
      description: "Vier Ziele pro Salve, dazu mehr Schaden.",
    },
    5: {
      attack: { targets: 5 },
      description: "Splittersturm: fünf Ziele pro Salve.",
    },
  }),
  jammer: attackTower({
    id: "jammer",
    name: "Störsender",
    role: "STÖRUNG",
    description: "Ein Puls schaltet 3 s lang Schild, Regeneration, Heilung, Tarnung, Ausweichen und Anführer-Bonus ab. Schilde brechen sofort.",
    cost: 130,
    damage: 5,
    range: 2.6,
    interval: 3,
    color: 0xff3df2,
    attack: { kind: "disrupt", radius: 1.1, duration: 3 },
    targets: ["ground", "air"],
    visual: { icon: "⌁", turret: "antenna" },
  }, {
    4: {
      attack: { radius: 1.3, duration: 3.5 },
      description: "Längere Störung in einem größeren Radius.",
    },
    5: {
      attack: { radius: 1.5, duration: 4.5 },
      description: "Funkstille: viereinhalb Sekunden Störung im weiten Radius.",
    },
  }),
  net: attackTower({
    id: "net",
    name: "Fangnetz",
    role: "LUFTFALLE",
    description: "Netzt Luftgegner 3 s lang ein: Sie fliegen 30 % langsamer und können auch von Bodentürmen wie Nova getroffen werden.",
    cost: 110,
    damage: 10,
    range: 3,
    interval: 1.6,
    color: 0xe0c068,
    attack: { kind: "net", factor: 0.7, duration: 3 },
    targets: ["air"],
    projectile: { speed: 9 },
    visual: { icon: "⌗", turret: "launcher", projectile: "net", impact: "spark" },
  }, {
    4: {
      attack: { duration: 3.5 },
      description: "Zähere Netze: halten 3,5 Sekunden, dazu mehr Schaden.",
    },
    5: {
      attack: { factor: 0.6, duration: 4.5 },
      description: "Stahlnetz: 40 % langsamer und viereinhalb Sekunden am Boden.",
    },
  }),
  refinery: {
    id: "refinery",
    name: "Raffinerie",
    role: "CREDITS",
    description: "Fördert nach jeder abgeschlossenen Welle 25 Credits. Kein eigener Angriff; lohnt sich, je früher sie steht.",
    cost: 120,
    damage: 0,
    range: 0,
    interval: 0,
    color: 0xf5c542,
    attack: { kind: "income", amount: 25 },
    targets: [],
    visual: { icon: "⚙\uFE0E", turret: "refinery" },
    upgrades: REFINERY_UPGRADES,
  },
  detector: {
    id: "detector",
    name: "Detektor",
    role: "AUFKLÄRUNG",
    description: "Deckt getarnte Gegner in seiner Reichweite auf, damit alle Türme sie anvisieren können. Kein eigener Angriff.",
    cost: 90,
    damage: 0,
    range: 3.5,
    interval: 0,
    color: 0x6fd3ff,
    attack: { kind: "detect" },
    targets: [],
    visual: { icon: "◎", turret: "radar" },
    upgrades: DETECTOR_UPGRADES,
  },
  beacon: {
    id: "beacon",
    name: "Prämienbake",
    role: "PRÄMIE",
    description: "Gegner, die in ihrem Radius besiegt werden, zahlen 50 % mehr Credits. Mehrere Baken zählen nicht doppelt. Kein eigener Angriff.",
    cost: 100,
    damage: 0,
    range: 2.5,
    interval: 0,
    color: 0xffd84d,
    attack: { kind: "bounty", bonus: 0.5 },
    targets: [],
    visual: { icon: "⛁\uFE0E", turret: "beacon" },
    upgrades: BEACON_UPGRADES,
  },
  dock: {
    id: "dock",
    name: "Reparaturdock",
    role: "REPARATUR",
    description: "Stellt nach jeder abgeschlossenen Welle 1 Reaktorenergie wieder her, höchstens bis zum Startwert. Kein eigener Angriff.",
    cost: 150,
    damage: 0,
    range: 0,
    interval: 0,
    color: 0x6dff9e,
    attack: { kind: "repair", amount: 1 },
    targets: [],
    visual: { icon: "✚\uFE0E", turret: "dock" },
    upgrades: DOCK_UPGRADES,
  },
  tracker: {
    id: "tracker",
    name: "Peilsender",
    role: "ZIELMARKIERUNG",
    description: "Gegner in seinem Radius erleiden 15 % mehr Schaden von allen Türmen, zusätzlich zu Korrosion. Kein eigener Angriff.",
    cost: 140,
    damage: 0,
    range: 2.2,
    interval: 0,
    color: 0xff5f6d,
    attack: { kind: "mark", amount: 0.15 },
    targets: [],
    visual: { icon: "⌾", turret: "tracker" },
    upgrades: TRACKER_UPGRADES,
  },
} satisfies Record<string, TowerDefinition>;
export const TOWERS: Readonly<Record<TowerId, Readonly<TowerDefinition>>> =
  TOWER_CONTENT;
