import type { TowerDefinition, TowerId } from "../core/types";
import { attackTower, AURA_UPGRADES, BEACON_UPGRADES, DETECTOR_UPGRADES, DOCK_UPGRADES, REFINERY_UPGRADES, TRACKER_UPGRADES, trapTower } from "./upgrades";
export const TOWER_CONTENT = {
  pulse: attackTower({
    id: "pulse",
    name: "Pulse",
    role: "SINGLE TARGET",
    description: "Fast, precise shots. Ideal against single enemies.",
    cost: 80,
    damage: 18,
    range: 2.65,
    interval: 0.55,
    color: 0x93f5b8,
    attack: { kind: "direct" },
    targets: ["ground", "air"],
    projectile: { speed: 10 },
    visual: { icon: "◉", turret: "barrel", projectile: "tracer", impact: "spark" },
  }),
  blast: attackTower({
    id: "blast",
    name: "Nova",
    role: "AREA DAMAGE",
    description: "Hits all enemies in the blast radius. Strong against groups.",
    cost: 130,
    damage: 40,
    range: 2.9,
    interval: 1.5,
    color: 0xffbd76,
    attack: { kind: "splash", radius: 1.25 },
    targets: ["ground"],
    projectile: { speed: 6 },
    visual: { icon: "✦", turret: "heavy", projectile: "shell", impact: "burst" },
  }),
  frost: attackTower({
    id: "frost",
    name: "Cryo",
    role: "SLOWING",
    description: "Slows a target by 45%. Buys other towers more time.",
    cost: 100,
    damage: 9,
    range: 2.5,
    interval: 0.7,
    color: 0xa5a2ff,
    attack: { kind: "slow", factor: 0.55, duration: 1.9 },
    targets: ["ground", "air"],
    projectile: { speed: 8 },
    visual: { icon: "❖", turret: "crystal", projectile: "crystal", impact: "spark" },
  }, {
    4: {
      attack: { factor: 0.45, duration: 2.3 },
      description: "Stronger and longer slow, plus more damage and range.",
    },
    5: {
      attack: { factor: 0.35, duration: 2.8 },
      description: "Deep Freeze: enemies move at only 35% speed for almost three seconds.",
    },
  }),
  aura: {
    id: "aura",
    name: "Aura",
    role: "SUPPORT",
    description: "Boosts attack towers in its radius. Pick one of three upgrade paths with three tiers each; no attack of its own.",
    cost: 160,
    damage: 0,
    range: 3,
    interval: 0,
    color: 0x78dfff,
    attack: { kind: "aura", base: { damage: 0, speed: 0, range: 0 } },
    targets: [],
    visual: {
      icon: "◎",
      turret: "aura",
      paths: {
        damage: { color: 0xff7a5c, motif: "blades" },
        speed: { color: 0xffd166, motif: "vortex" },
        range: { color: 0x8ef0a8, motif: "rings" },
      },
    },
    upgrades: AURA_UPGRADES,
  },
  flak: attackTower({
    id: "flak",
    name: "Flak",
    role: "ANTI-AIR",
    description: "Fast shots against air targets. Cannot hit ground units.",
    cost: 90,
    damage: 26,
    range: 3.2,
    interval: 0.45,
    color: 0xff9de2,
    attack: { kind: "direct" },
    targets: ["air"],
    projectile: { speed: 12 },
    visual: { icon: "⌖", turret: "twin", projectile: "twin", impact: "spark" },
  }),
  tesla: attackTower({
    id: "tesla",
    name: "Tesla",
    role: "CHAIN LIGHTNING",
    description: "The bolt jumps to further enemies nearby. Hits ground and air.",
    cost: 150,
    damage: 22,
    range: 2.6,
    interval: 1.1,
    color: 0xf7e46b,
    attack: { kind: "chain", jumps: 3, range: 1.6, falloff: 0.75 },
    targets: ["ground", "air"],
    visual: { icon: "ϟ", turret: "coil", muzzle: "bolt" },
  }, {
    4: {
      attack: { jumps: 4, range: 1.8 },
      description: "The bolt jumps to one more enemy and farther, plus more damage.",
    },
    5: {
      attack: { jumps: 5, range: 2 },
      description: "Storm Core: up to five jumps with two cells of range.",
    },
  }),
  lance: attackTower({
    id: "lance",
    name: "Lance",
    role: "PIERCING",
    description: "Long-range railgun. The beam pierces every enemy on its line.",
    cost: 170,
    damage: 70,
    range: 4.4,
    interval: 2.4,
    color: 0xe8f1ff,
    attack: { kind: "pierce", width: 0.35, falloff: 0.85 },
    targets: ["ground", "air"],
    visual: { icon: "⟂", turret: "rail" },
  }, {
    4: {
      attack: { falloff: 0.9 },
      description: "Dense Beam: loses less damage per enemy pierced.",
    },
    5: {
      attack: { width: 0.5, falloff: 1 },
      description: "Particle Lance: wider beam, every enemy on the line takes full damage.",
    },
  }),
  inferno: attackTower({
    id: "inferno",
    name: "Ember",
    role: "BURN DAMAGE",
    description: "Sets enemies on fire. The burn deals 2.5 times the hit over three seconds.",
    cost: 120,
    damage: 10,
    range: 2.4,
    interval: 0.8,
    color: 0xff6a3d,
    attack: { kind: "burn", ratio: 2.5, duration: 3 },
    targets: ["ground", "air"],
    projectile: { speed: 7 },
    visual: { icon: "♨\uFE0E", turret: "flame", projectile: "ember", impact: "spark" },
  }, {
    4: {
      attack: { ratio: 3 },
      description: "Hotter Embers: the burn deals three times the hit.",
    },
    5: {
      attack: { ratio: 3.5, duration: 3.5 },
      description: "Firestorm: stronger and longer burn.",
    },
  }),
  stasis: attackTower({
    id: "stasis",
    name: "Stasis",
    role: "STUN",
    description: "A pulse briefly halts all enemies in its radius. They are then immune for 1.5 s.",
    cost: 140,
    damage: 6,
    range: 2.4,
    interval: 3,
    color: 0x5cf2d6,
    attack: { kind: "stun", radius: 0.9, duration: 0.8, recovery: 1.5 },
    targets: ["ground", "air"],
    visual: { icon: "⊛", turret: "emitter" },
  }, {
    4: {
      attack: { duration: 1, radius: 1.1 },
      description: "Longer stun in a larger radius.",
    },
    5: {
      attack: { duration: 1.2, radius: 1.3 },
      description: "Time Trap: enemies in the wide radius stand still for 1.2 seconds.",
    },
  }),
  acid: attackTower({
    id: "acid",
    name: "Korrosion",
    role: "WEAKENING",
    description: "Acid in a small radius. Enemies hit take 25% more damage from all towers for 3 s.",
    cost: 110,
    damage: 12,
    range: 2.7,
    interval: 1.2,
    color: 0xb6f04a,
    attack: { kind: "corrode", radius: 0.8, amount: 0.25, duration: 3 },
    targets: ["ground", "air"],
    projectile: { speed: 6 },
    visual: { icon: "☣\uFE0E", turret: "vat", projectile: "glob", impact: "burst" },
  }, {
    4: {
      attack: { amount: 0.3 },
      description: "Concentrated Acid: enemies take 30% more damage.",
    },
    5: {
      attack: { amount: 0.4, radius: 1 },
      description: "Dissolution: 40% more damage in a larger radius.",
    },
  }),
  decay: attackTower({
    id: "decay",
    name: "Decay",
    role: "ANTI-BOSS",
    description: "Every hit also removes 4% of maximum HP. Strong against Tanks and Titans.",
    cost: 160,
    damage: 20,
    range: 3,
    interval: 2,
    color: 0xd16bff,
    attack: { kind: "decay", percent: 0.04 },
    targets: ["ground", "air"],
    projectile: { speed: 9 },
    visual: { icon: "⬡", turret: "prism", projectile: "orb", impact: "burst" },
  }, {
    4: {
      attack: { percent: 0.05 },
      description: "Deeper Decay: 5% of maximum HP per hit.",
    },
    5: {
      attack: { percent: 0.06 },
      description: "Disintegration: 6% of maximum HP per hit.",
    },
  }),
  focus: attackTower({
    id: "focus",
    name: "Focus",
    role: "CHARGE-UP",
    description: "Continuous beam that locks onto its target. Every follow-up hit on the same target deals 20% more damage, up to triple.",
    cost: 150,
    damage: 6,
    range: 2.8,
    interval: 0.3,
    color: 0xff4f8b,
    attack: { kind: "focus", ramp: 0.2, stacks: 10 },
    targets: ["ground", "air"],
    visual: { icon: "◈", turret: "lens" },
  }, {
    4: {
      attack: { ramp: 0.25 },
      description: "Faster Charge: 25% more damage per follow-up hit.",
    },
    5: {
      attack: { ramp: 0.3, stacks: 12 },
      description: "Magnifying Glass: 30% per follow-up hit and two more steps, up to 4.6 times.",
    },
  }),
  gravity: attackTower({
    id: "gravity",
    name: "Gravitron",
    role: "KNOCKBACK",
    description: "A gravity pulse pulls ground enemies in its radius backward along the path for 0.6 s. They are then immune for 2.5 s.",
    cost: 170,
    damage: 8,
    range: 2.5,
    interval: 4,
    color: 0x4d7cff,
    attack: { kind: "pull", radius: 1, strength: 1.5, duration: 0.6, recovery: 2.5 },
    targets: ["ground"],
    visual: { icon: "⊚", turret: "gravity" },
  }, {
    4: {
      attack: { radius: 1.2, strength: 1.8 },
      description: "Stronger pull in a larger radius.",
    },
    5: {
      attack: { radius: 1.4, strength: 2.2, duration: 0.7 },
      description: "Event Horizon: enemies in the wide radius are pulled back longer and harder.",
    },
  }),
  mortar: attackTower({
    id: "mortar",
    name: "Mortar",
    role: "ARTILLERY",
    description: "Slow shells with long range and a large blast radius. Cannot fire at enemies closer than 1.5 cells.",
    cost: 160,
    damage: 60,
    range: 5,
    interval: 3,
    color: 0xc8a46e,
    attack: { kind: "mortar", radius: 1.3, minRange: 1.5 },
    targets: ["ground"],
    projectile: { speed: 4 },
    visual: { icon: "⌓", turret: "mortar", projectile: "shell", impact: "burst" },
  }, {
    4: {
      attack: { radius: 1.5 },
      description: "Heavier Shells: larger blast radius, plus more damage.",
    },
    5: {
      attack: { radius: 1.7, minRange: 1.2 },
      description: "Howitzer: huge blast radius and a smaller dead zone.",
    },
  }),
  quake: attackTower({
    id: "quake",
    name: "Quake",
    role: "CLOSE RANGE",
    description: "A shockwave hits all ground enemies in range, full damage near the tower, half at the edge. Strong at bends.",
    cost: 140,
    damage: 30,
    range: 1.8,
    interval: 1.8,
    color: 0xa4703f,
    attack: { kind: "quake", edge: 0.5 },
    targets: ["ground"],
    visual: { icon: "≋", turret: "hammer" },
  }, {
    4: {
      attack: { edge: 0.7 },
      description: "Deeper Wave: 70% damage at the edge, plus more damage and range.",
    },
    5: {
      attack: { edge: 1 },
      description: "Tremor: full force out to the edge of its range.",
    },
  }),
  executioner: attackTower({
    id: "executioner",
    name: "Executioner",
    role: "EXECUTION",
    description: "Heavy shots. Enemies below 25% HP take four times the damage on impact. Ideal for finishing off wounded targets.",
    cost: 150,
    damage: 40,
    range: 3,
    interval: 1.6,
    color: 0xb3122e,
    attack: { kind: "execute", threshold: 0.25, multiplier: 4 },
    targets: ["ground", "air"],
    projectile: { speed: 11 },
    visual: { icon: "⚔\uFE0E", turret: "blade", projectile: "tracer", impact: "spark" },
  }, {
    4: {
      attack: { threshold: 0.3 },
      description: "Execution already below 30% HP, plus more damage.",
    },
    5: {
      attack: { threshold: 0.35, multiplier: 5 },
      description: "Headsman: five times the damage below 35% HP.",
    },
  }),
  shrapnel: attackTower({
    id: "shrapnel",
    name: "Shrapnel",
    role: "MULTI-TARGET",
    description: "Every salvo hits up to three different enemies at once. Strong against swarms on the ground and in the air.",
    cost: 130,
    damage: 14,
    range: 2.6,
    interval: 0.9,
    color: 0x9fb4c7,
    attack: { kind: "volley", targets: 3 },
    targets: ["ground", "air"],
    projectile: { speed: 11 },
    visual: { icon: "⁂", turret: "scatter", projectile: "crystal", impact: "spark" },
  }, {
    4: {
      attack: { targets: 4 },
      description: "Four targets per salvo, plus more damage.",
    },
    5: {
      attack: { targets: 5 },
      description: "Fragment Storm: five targets per salvo.",
    },
  }),
  jammer: attackTower({
    id: "jammer",
    name: "Jammer",
    role: "DISRUPTION",
    description: "A pulse disables Shield, Regeneration, Healing, Stealth, Evasion and Leader bonus for 3 s. Shields break instantly.",
    cost: 130,
    damage: 5,
    range: 2.6,
    interval: 3,
    color: 0xff3df2,
    attack: { kind: "disrupt", radius: 1.1, duration: 3 },
    targets: ["ground", "air"],
    visual: { icon: "⌁", turret: "antenna" },
  }, {
    4: {
      attack: { radius: 1.3, duration: 3.5 },
      description: "Longer disruption in a larger radius.",
    },
    5: {
      attack: { radius: 1.5, duration: 4.5 },
      description: "Radio Silence: four and a half seconds of disruption in the wide radius.",
    },
  }),
  net: attackTower({
    id: "net",
    name: "Snare Net",
    role: "AIR TRAP",
    description: "Nets air enemies for 3 s: they fly 30% slower and can also be hit by ground towers such as Nova.",
    cost: 110,
    damage: 10,
    range: 3,
    interval: 1.6,
    color: 0xe0c068,
    attack: { kind: "net", factor: 0.7, duration: 3 },
    targets: ["air"],
    projectile: { speed: 9 },
    visual: { icon: "⌗", turret: "launcher", projectile: "net", impact: "spark" },
  }, {
    4: {
      attack: { duration: 3.5 },
      description: "Tougher Nets: last 3.5 seconds, plus more damage.",
    },
    5: {
      attack: { factor: 0.6, duration: 4.5 },
      description: "Steel Net: 40% slower and four and a half seconds on the ground.",
    },
  }),
  // Traps: built on path cells, triggered by ground enemies walking over them, stealthed ones included.
  mine: trapTower({
    id: "mine",
    name: "Mine",
    role: "EXPLOSIVE TRAP",
    description: "Explodes as soon as a ground enemy walks over it and hits all ground enemies in radius 1.1. Needs 5 s to reload.",
    cost: 70,
    damage: 80,
    range: 0.45,
    interval: 5,
    color: 0xff8c42,
    attack: { kind: "splash", radius: 1.1 },
    targets: ["ground"],
    visual: { icon: "✷", turret: "mine", impact: "burst" },
  }, {
    4: { attack: { radius: 1.3 }, description: "Bigger Charge: blast radius 1.3, plus more damage." },
    5: { attack: { radius: 1.5 }, description: "Shard Mine: blast radius 1.5." },
  }),
  spikes: trapTower({
    id: "spikes",
    name: "Caltrops",
    role: "BLEEDING",
    description: "Anything that walks over them bleeds for 4 s: 12 damage for every further cell it walks. Fast enemies suffer most, held ones not at all.",
    cost: 60,
    damage: 4,
    range: 0.5,
    interval: 0.5,
    color: 0xc9d1d9,
    attack: { kind: "bleed", perCell: 12, duration: 4 },
    targets: ["ground"],
    visual: { icon: "⩚", turret: "spikes" },
  }, {
    4: { attack: { perCell: 15 }, description: "Sharper Spikes: 15 damage per cell walked." },
    5: { attack: { perCell: 18, duration: 5 }, description: "Barbs: 18 damage per cell, for five seconds." },
  }),
  tar: trapTower({
    id: "tar",
    name: "Tar Pit",
    role: "SLOWING",
    description: "Every ground enemy that wades through sticks and keeps moving at 45% speed for 1.5 s.",
    cost: 60,
    damage: 2,
    range: 0.45,
    interval: 0.25,
    color: 0x6b5a7a,
    attack: { kind: "slow", factor: 0.45, duration: 1.5 },
    targets: ["ground"],
    visual: { icon: "◍", turret: "tar" },
  }, {
    4: { attack: { factor: 0.4, duration: 2 }, description: "Stickier Tar: 40% speed for 2 s." },
    5: { attack: { factor: 0.3, duration: 2.5 }, description: "Pitch Bog: 30% speed for 2.5 s." },
  }),
  snare: trapTower({
    id: "snare",
    name: "Bear Trap",
    role: "HOLDING",
    description: "Snaps shut and holds all ground enemies on the cell for 1.5 s. They are then immune for 2.5 s; the trap needs 4 s to reset.",
    cost: 90,
    damage: 30,
    range: 0.45,
    interval: 4,
    color: 0x8a96a3,
    attack: { kind: "stun", radius: 0.5, duration: 1.5, recovery: 2.5 },
    targets: ["ground"],
    visual: { icon: "⌬", turret: "snare" },
  }, {
    4: { attack: { duration: 1.8 }, description: "Stronger Spring: holds for 1.8 s." },
    5: { attack: { duration: 2.2, radius: 0.7 }, description: "Double Trap: holds for 2.2 s and also grabs enemies next to it." },
  }),
  grill: trapTower({
    id: "grill",
    name: "Flame Grate",
    role: "FIRE",
    description: "Sets ground enemies that walk over it on fire. The burn deals three times the hit over three seconds.",
    cost: 80,
    damage: 8,
    range: 0.45,
    interval: 0.6,
    color: 0xff5a1f,
    attack: { kind: "burn", ratio: 3, duration: 3 },
    targets: ["ground"],
    visual: { icon: "▦", turret: "grill" },
  }, {
    4: { attack: { ratio: 3.5 }, description: "Hotter Grate: the burn deals 3.5 times." },
    5: { attack: { ratio: 4, duration: 4 }, description: "Bed of Coals: four times over four seconds." },
  }),
  spring: trapTower({
    id: "spring",
    name: "Spring",
    role: "THROWBACK",
    description: "Hurls ground enemies on the cell back along the path. They are then immune for 3 s; the spring takes 3.5 s to re-arm. Berserkers resist.",
    cost: 100,
    damage: 10,
    range: 0.45,
    interval: 3.5,
    color: 0x5ce1a0,
    attack: { kind: "pull", radius: 0.5, strength: 2.5, duration: 0.6, recovery: 3 },
    targets: ["ground"],
    visual: { icon: "⌇", turret: "spring" },
  }, {
    4: { attack: { strength: 3 }, description: "Stronger Spring: throws farther back." },
    5: { attack: { strength: 3.5, duration: 0.7 }, description: "Catapult: throws almost three cells back." },
  }),
  limpet: trapTower({
    id: "limpet",
    name: "Sticky Mine",
    role: "TIME FUSE",
    description: "Attaches a bomb to the enemy that explodes 2 s later in the middle of its group (radius 1.2). If the carrier dies first, it goes off at once, and bomb carriers caught in the blast explode too.",
    cost: 90,
    damage: 70,
    range: 0.45,
    interval: 3,
    color: 0xff4d4d,
    attack: { kind: "charge", fuse: 2, radius: 1.2 },
    targets: ["ground"],
    visual: { icon: "⊗", turret: "limpet" },
  }, {
    4: { attack: { radius: 1.4 }, description: "Stronger Charge: blast radius 1.4, plus more damage." },
    5: { attack: { radius: 1.6, fuse: 1.5 }, description: "Quick Fuse: radius 1.6, explosion after only 1.5 s." },
  }),
  pit: trapTower({
    id: "pit",
    name: "Pitfall",
    role: "SWALLOW",
    description: "Small enemies such as Drones, Runners, Skaters, Phantoms, Blinkers, Packwolves and Jump Beetles fall in and are defeated instantly, no matter how much HP they have. Larger ones only take damage. Needs 6 s to cover up.",
    cost: 120,
    damage: 60,
    range: 0.45,
    interval: 6,
    color: 0x8b6b4a,
    attack: { kind: "pit", size: 0.2 },
    targets: ["ground"],
    visual: { icon: "◌", turret: "pit" },
  }, {
    4: { attack: { size: 0.25 }, description: "Deeper Pit: also swallows Healers, Shield Bearers, Shards, Sludges, Prism Runners, Salamanders and Pioneers." },
    5: { attack: { size: 0.28 }, description: "Abyss: even swallows Tanks and Null-Field Carriers. Berserkers and Titans never fall in." },
  }),
  tripwire: trapTower({
    id: "tripwire",
    name: "Tripwire",
    role: "AMBUSH",
    description: "A trip wire: whoever triggers it instantly reloads all attack towers in radius 2.5 so they fire together. Needs 6 s to set.",
    cost: 110,
    damage: 5,
    range: 0.45,
    interval: 6,
    color: 0xffe066,
    attack: { kind: "alarm", radius: 2.5 },
    targets: ["ground"],
    visual: { icon: "⌯", turret: "tripwire" },
  }, {
    4: { attack: { radius: 3 }, description: "Longer Wire: alerts towers in radius 3." },
    5: { attack: { radius: 3.5 }, description: "Full Alert: alerts towers in radius 3.5." },
  }),
  refinery: {
    id: "refinery",
    name: "Refinery",
    role: "CREDITS",
    description: "Produces 25 credits after every completed wave. No attack of its own; the earlier it stands, the more it pays off.",
    cost: 120,
    damage: 0,
    range: 0,
    interval: 0,
    color: 0xf5c542,
    attack: { kind: "income", amount: 25 },
    targets: [],
    visual: { icon: "⚙\uFE0E", turret: "refinery" },
    upgrades: REFINERY_UPGRADES,
  },
  detector: {
    id: "detector",
    name: "Detector",
    role: "RECON",
    description: "Reveals stealthed enemies in its range so all towers can target them. No attack of its own.",
    cost: 90,
    damage: 0,
    range: 3.5,
    interval: 0,
    color: 0x6fd3ff,
    attack: { kind: "detect" },
    targets: [],
    visual: { icon: "◎", turret: "radar" },
    upgrades: DETECTOR_UPGRADES,
  },
  beacon: {
    id: "beacon",
    name: "Bounty Beacon",
    role: "BOUNTY",
    description: "Enemies defeated in its radius pay 50% more credits. Multiple beacons do not stack. No attack of its own.",
    cost: 100,
    damage: 0,
    range: 2.5,
    interval: 0,
    color: 0xffd84d,
    attack: { kind: "bounty", bonus: 0.5 },
    targets: [],
    visual: { icon: "⛁\uFE0E", turret: "beacon" },
    upgrades: BEACON_UPGRADES,
  },
  dock: {
    id: "dock",
    name: "Repair Dock",
    role: "REPAIR",
    description: "Restores 1 reactor energy after every completed wave, up to the starting value at most. No attack of its own.",
    cost: 150,
    damage: 0,
    range: 0,
    interval: 0,
    color: 0x6dff9e,
    attack: { kind: "repair", amount: 1 },
    targets: [],
    visual: { icon: "✚\uFE0E", turret: "dock" },
    upgrades: DOCK_UPGRADES,
  },
  tracker: {
    id: "tracker",
    name: "Tracker",
    role: "TARGET MARKING",
    description: "Enemies in its radius take 15% more damage from all towers, on top of Corrosion. No attack of its own.",
    cost: 140,
    damage: 0,
    range: 2.2,
    interval: 0,
    color: 0xff5f6d,
    attack: { kind: "mark", amount: 0.15 },
    targets: [],
    visual: { icon: "⌾", turret: "tracker" },
    upgrades: TRACKER_UPGRADES,
  },
} satisfies Record<string, TowerDefinition>;
export const TOWERS: Readonly<Record<TowerId, Readonly<TowerDefinition>>> =
  TOWER_CONTENT;
